### PR TITLE
Enhance HttpUtils class and add a hello-world alert plugin example

### PR DESCRIPTION
**Pull request by hgaol**
## What is the purpose of the pull request

Enhance `HttpUtils` class.
Added a hello-world alert plugin example.

## Verify this pull request

- Added related tests in `HttpUtilsTest`
- Added related tests for hello-world alert plugin example.

### CODE REVIEW

**Comment by hgaol** [comment]
Anyone free to review this small PR?

**Comment by hgaol** [comment]
When it's ready to merge, pls let me know and I could rebase to make the commit history clean. Thanks.

**Comment by dailidong** [comment]
@lgcareer please review this PR

**Comment by lgcareer** [comment]
The dolphinscheduler-plugin-api is a new module,Whether need add a module in order to add alert plugin?

**Comment by lgcareer** [comment]
> Anyone free to review this small PR?

I saw you send the email about `[PROPOSAL][Feature] Support plugin in Alert service`,So sorry didn't  reply in time.

**Comment by hgaol** [comment]
> > Anyone free to review this small PR?
> 
> I saw you send the email about `[PROPOSAL][Feature] Support plugin in Alert service`,So sorry didn't reply in time.

Easy bro, feel free to let me know if any suggestion.

**Comment by hgaol** [comment]
I remove examples from root pom file, and make it a pure directory. Also changed the return type of the alert plugin interface to avoid confusion.
Hi @lgcareer , pls tell me if any suggestion.

**Comment by hgaol** [comment]
Hi guys, this PR has be there for a long time. Is there any suggestion or is there a plan to support alert plugin?
If any suggestion, I could fix it.
If no plan to support alert plugin, I'll close this PR.
Thanks

**Comment by gabrywu** [comment]
> Hi guys, this PR has been here for long time. Is there any suggestion or is there a plan to support alert plugin?
> If any suggestion, I could fix it.
> If no plan to support alert plugin, I'll close this PR.
> Thanks! @lgcareer @dailidong

I think the subject has been discussed in the dev email thread , welcome to join the email to talk about this.  You can invite @lgcareer to review this PR

**Comment by hgaol** [comment]
Since this PR has been here for long time and no review, it may not be align with DS's roadmap. Now I will close this PR.

**Pull request closed without merging**
