### PR TITLE
[Fix-3351][ui] process_definition_json contains definitionList，but this definitionList is not use

### PR DESCRIPTION
**Pull request by JinyLeeChina**
#3351

### CODE REVIEW

**Comment by break60** [comment]
3300pr also changed the action.js file

**Comment by JinyLeeChina** [comment]
That should be closed, because it contains 3299 and 3351 issue. I think one pr fixed one issue

**Comment by lenboo** [comment]
> That should be closed, because it contains 3299 and 3351 issue. I think one pr fixed one issue

i will colse it.

**Comment by break60** [comment]
> > That should be closed, because it contains 3299 and 3351 issue. I think one pr fixed one issue
> 
> i will colse it.

Did you close it wrong

**Pull request merged**
