### PR TITLE
replace CollectionUtils deprecated method

### PR DESCRIPTION
**Pull request by CalvinKirs**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

replace CollectionUtils deprecated method

## Verify this pull request

*(Please pick either of the following options)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
BeanUtils Check dependency license,so,I copied it to my project

**Comment by gabrywu** [comment]
@CalvinKirs SonarCloud Code Analysis test failed

**Comment by CalvinKirs** [comment]
> @CalvinKirs SonarCloud Code Analysis test failed

commons-bean Check dependency license fail ,so,I copied bean-map to my project,I don’t know if it’s acceptable or not, I hope to get some suggestions from you

**Comment by gabrywu** [comment]
> > @CalvinKirs SonarCloud Code Analysis test failed
> 
> commons-bean Check dependency license fail ,so,I copied bean-map to my project,I don’t know if it’s acceptable or not, I hope to get some suggestions from you

@CalvinKirs If the beanMap class deprecated, so there is an alternative ? Only copying it might not be a good solution

**Comment by CalvinKirs** [comment]
> > > @CalvinKirs SonarCloud Code Analysis test failed
> > 
> > 
> > commons-bean Check dependency license fail ,so,I copied bean-map to my project,I don’t know if it’s acceptable or not, I hope to get some suggestions from you
> 
> @CalvinKirs If the beanMap class deprecated, so there is an alternative ? Only copying it might not be a good solution

Thank you very much for your suggestion. You are right. In fact, I also feel that it is rude to directly copy this method,  I think I can achieve the same function in other ways. I will finish it later. it.

**Comment by CalvinKirs** [comment]
> > > @CalvinKirs SonarCloud Code Analysis test failed
> > 
> > 
> > commons-bean Check dependency license fail ,so,I copied bean-map to my project,I don’t know if it’s acceptable or not, I hope to get some suggestions from you
> 
> @CalvinKirs If the beanMap class deprecated, so there is an alternative ? Only copying it might not be a good solution

Thank you very much for your suggestion. You are right. In fact, I also feel that it is rude to directly copy this method,  I think I can achieve the same function in other ways. I will finish it later it.

**Comment by CalvinKirs** [comment]
I have completed the change, I’m sorry to trouble you to have time to review @gabrywu

**Comment by lgcareer** [comment]
Hi,you should describe detail as following when update the pom dependency.
1、Which pom dependecncy you removed?And which jar removed? 
2、 Which pom dependecncy you added?And which jar added?
Except for the above,You should give the github usrl of the dependency version.

**Comment by CalvinKirs** [comment]
> Hi,you should describe detail as following when update the pom dependency.
> 1、Which pom dependency you removed?And which jar removed?
> 2、 Which pom dependency you added?And which jar added?
> Except for the above,You should give the github usrl of the dependency version.

Thank you very much for your review. I didn’t remove the jar. I changed it to beanMap because the original method was deprecated. I added common-beanutils, which was originally in the parent pom, but no license was added, I fixed it It, its address is https://github.com/apache/commons-beanutils

**Comment by qiaozhanwei** [comment]
please resolve conflicting files . Thx

**Comment by CalvinKirs** [comment]
> please resolve conflicting files . Thx

Thanks for your review, I have completed the changes, please check again, Thx

**Pull request merged**
