### PR TITLE
[BUG] ProcessUtils.kill blocked

### PR DESCRIPTION
**Pull request by gabrywu**
check yarn task when killYarnJob.  https://github.com/apache/incubator-dolphinscheduler/issues/1947

### CODE REVIEW

**Comment by dailidong** [comment]
> sorry， I think this is simple . because shell can run MR or Spark or Flink task
> I think it necessary add filed to controller whether yarn task

anybody who has good idea to solve this problem?

**Comment by Jave-Chen** [comment]
Add a include record at pom.xml will get right coverage.

**Comment by Jave-Chen** [comment]
> sorry， I think this is simple . because shell can run MR or Spark or Flink task
> I think it necessary add filed to controller whether yarn task

I think we should add a killType not taskType. 
For example, killType = KILL_BY_ID will killl task by task id, killType = KiLL_BY_LOG will kill task by log content.

**Comment by gabrywu** [comment]
> 
> 
> Add a include record at pom.xml will get right coverage.

added

**Comment by qiaozhanwei** [comment]
> > sorry， I think this is simple . because shell can run MR or Spark or Flink task
> > I think it necessary add filed to controller whether yarn task
> 
> I think we should add a killType not taskType.
> For example, killType = KILL_BY_ID will killl task by task id, killType = KiLL_BY_LOG will kill task by log content.

Not only kill task need to read task log , for example whether SHELL task status success or failure ,
first of all judge shell exit code  status , second judge for yarn or messos resources negotiator status . so necessary resources negotiator type to user choice

**Comment by Jave-Chen** [comment]
> > I think we should add a killType not taskType.
> > For example, killType = KILL_BY_ID will killl task by task id, killType = KiLL_BY_LOG will kill task by log content.
> 
> Not only kill task need to read task log , for example whether SHELL task status success or failure ,
> first of all judge shell exit code status , second judge for yarn or messos resources negotiator status . so necessary resources negotiator type to user choice
agree

**Pull request closed without merging**
