### PR TITLE
[Feature][process_definition] process definition need to support parallel or serial choose

### PR DESCRIPTION
**Pull request by 597365581**
process definition need to support parallel or serial choose.
if is serial in dispatch，need to the previous process_instance execute complete，next process_instance can to run。

流程实例中支持并发并行和串行。 如果是串行处理，需要等待上一个流程实例运行完成后，下一个流程实例才可以运行。
如果是并行处理，则不需要。

### CODE REVIEW

**Comment by break60** [comment]
Why have so many files changed

**Review by 597365581 — COMMENTED** [review]
image

**Review by 597365581 — COMMENTED** [review]
[Feature][process_definition] process definition need to support parallel or serial choose.

**Comment by 597365581** [comment]
> Why have so many files changed

I don't know，I only  dev [Feature][process_definition] process definition need to support parallel or serial choose. #3662 ,and push and pull request.

**Comment by 597365581** [comment]
@break60  please confirm?

**Comment by xingchun-chen** [comment]
Please pull the latest dev code and resolve conflict files

**Comment by chengshiwen** [comment]
@597365581  What is the relationship between these 3 PRs: #3684, #3685, #3728? 
Is this duplicated with #3728?

**Comment by kamiljune** [comment]
Hi @597365581 ,
Why close this issue? 
I think serial and parallel control for instance is a must-have function for workflow, just like Azkaban and others

**Pull request closed without merging**
