### PR TITLE
[FIX-3836][1.3.3-release-API] process definition validation name interface prompt information error 

### LINKED ISSUE #3836: [Bug][API] verifyProcessDefinitionName error message
image

### PR DESCRIPTION
**Pull request by BoYiZhang**
process definition validation name interface prompt information error

this close #3836

### CODE REVIEW

**Review by lgcareer — APPROVED** [review]
+1

**Comment by lenboo** [comment]
@BoYiZhang 
please solve the code smell problem
then another pr to dev branch is needed.

**Comment by BoYiZhang** [comment]
> @BoYiZhang
> please solve the code smell problem
> then another pr to dev branch is needed.
-----------------------------------------
fix code smell
dev branch can merge 1.3.3  ,  No more repeat submission

**Comment by lenboo** [comment]
> > @BoYiZhang
> > please solve the code smell problem
> > then another pr to dev branch is needed.
> 
> fix code smell
> dev branch can merge 1.3.3 , No more repeat submission

it's better submit pr on dev in time, if not, it will take more time in the future.

**Comment by BoYiZhang** [comment]
> > > @BoYiZhang
> > > please solve the code smell problem
> > > then another pr to dev branch is needed.
> > 
> > 
> > fix code smell
> > dev branch can merge 1.3.3 , No more repeat submission
> 
> it's better submit pr on dev in time, if not, it will take more time in the future.

Now there are some differences between 1.3.3 and dev branch, especially with codestyle

If two copies of the same PR are submitted, then it is very troublesome to review.

What's your opinion?

**Comment by lenboo** [comment]
> > > > @BoYiZhang
> > > > please solve the code smell problem
> > > > then another pr to dev branch is needed.
> > > 
> > > 
> > > fix code smell
> > > dev branch can merge 1.3.3 , No more repeat submission
> > 
> > 
> > it's better submit pr on dev in time, if not, it will take more time in the future.
> 
> Now there are some differences between 1.3.3 and dev branch, especially with codestyle
> 
> If two copies of the same PR are submitted, then it is very troublesome to review.
> 
> What's your opinion?

i think you can submit 

> > > > @BoYiZhang
> > > > please solve the code smell problem
> > > > then another pr to dev branch is needed.
> > > 
> > > 
> > > fix code smell
> > > dev branch can merge 1.3.3 , No more repeat submission
> > 
> > 
> > it's better submit pr on dev in time, if not, it will take more time in the future.
> 
> Now there are some differences between 1.3.3 and dev branch, especially with codestyle
> 
> If two copies of the same PR are submitted, then it is very troublesome to review.
> 
> What's your opinion?

you are right, there would be troublesome to review. but it will be more difficult to merge two branches in the future. 
By contrast, it would be easier for us to merge the changes at the moment.

**Comment by BoYiZhang** [comment]
> merge

ok



> > > > > @BoYiZhang
> > > > > please solve the code smell problem
> > > > > then another pr to dev branch is needed.
> > > > 
> > > > 
> > > > fix code smell
> > > > dev branch can merge 1.3.3 , No more repeat submission
> > > 
> > > 
> > > it's better submit pr on dev in time, if not, it will take more time in the future.
> > 
> > 
> > Now there are some differences between 1.3.3 and dev branch, especially with codestyle
> > If two copies of the same PR are submitted, then it is very troublesome to review.
> > What's your opinion?
> 
> i think you can submit
> 
> > > > > @BoYiZhang
> > > > > please solve the code smell problem
> > > > > then another pr to dev branch is needed.
> > > > 
> > > > 
> > > > fix code smell
> > > > dev branch can merge 1.3.3 , No more repeat submission
> > > 
> > > 
> > > it's better submit pr on dev in time, if not, it will take more time in the future.
> > 
> > 
> > Now there are some differences between 1.3.3 and dev branch, especially with codestyle
> > If two copies of the same PR are submitted, then it is very troublesome to review.
> > What's your opinion?
> 
> you are right, there would be troublesome to review. but it will be more difficult to merge two branches in the future.
> By contrast, it would be easier for us to merge the changes at the moment.

ok
this pr to dev branch ..
https://github.com/apache/incubator-dolphinscheduler/pull/3908

**Pull request merged**
