### PR TITLE
[Improvement][server] WATERDROP task plug-in optimization in switch case code cleaning.

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request
[server] WATERDROP task plug-in optimization in switch case code cleaning.

## Brief change log

Clean up duplicate code

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by zixi0825** [comment]
+1

**Comment by zhuangchong** [comment]
@dailidong  Help. This branch code is switch case code cleaning. Can you merge Dev ? thx.

**Review by CalvinKirs — APPROVED** [review]
LGTM,Please confirm again  @qiaozhanwei @dailidong

**Comment by zhuangchong** [comment]
@qiaozhanwei @dailidong  Help. This branch code is switch case code cleaning. Can you merge Dev ? thx.

**Pull request closed without merging**
