### PR TITLE
fix [BUG] TaskExecutionContextCacheManagerImpl Do not execute removeB…

### PR DESCRIPTION
**Pull request by 1445103710**
…yTaskInstanceId #2745

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

This pull request adds remove taskExecutionContextCacheManager cache

## Brief change log

*(for example:)*
  - *Add maven-checkstyle-plugin to root pom.xml*
add remove taskExecutionContextCacheManager to TaskExecuteThread
add remove taskExecutionContextCacheManager to TaskKillProcessor
## Verify this pull request

This pull request is already covered by existing tests, such as *(TaskCallbackServiceTest)*.

### CODE REVIEW

**Comment by gabrywu** [comment]
@1445103710  Can you close the duplicated PR and resolve the Unit Test error?
https://github.com/apache/incubator-dolphinscheduler/pull/2752

**Comment by dailidong** [comment]
the bug in the dev-1.3.0 will be more attentive and reviewed quickly, so I  reopen this PR

**Comment by dailidong** [comment]
if UT go through, i will merge it

**Comment by dailidong** [comment]
Unit Test failed

**Comment by dailidong** [comment]
> Unit Test failed

failed ut not relevant about this PR

**Comment by dailidong** [comment]
thanks for your first contribution，looking forward for your next contribution, if you need help, please contact me through mail or add my wechat(510570367), when added, please tell me your github id, thx

**Pull request merged**
