### PR TITLE
[Improvement][server]lower weight round robin  support weight

### PR DESCRIPTION
**Pull request by CalvinKirs**
## What is the purpose of the pull request

lower weight round robin  support weight
## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by gaojun2048 — COMMENTED** [review]
+1

**Review by qiaozhanwei — APPROVED** [review]
+1

**Comment by qiaozhanwei** [comment]
please resolve conflicts . Thx

**Comment by CalvinKirs** [comment]
> please resolve conflicts . Thx

Thank you very much for your review, I will finish it later

**Review by gaojun2048 — APPROVED** [review]
+1

**Pull request merged**
