### PR TITLE
[Improvement][remote] improvement netty eventLoopGroup

### PR DESCRIPTION
**Pull request by CalvinKirs**
improvement netty eventLoopGroup
If you are running on linux you can use EpollEventLoopGroup and so get better performance, less GC and have more advanced features that are only available on linux.

## Verify this pull request

UT

### CODE REVIEW

**Review by qiaozhanwei — APPROVED** [review]
+1

**Comment by CalvinKirs** [comment]
> +1
> 
> please fix SonarCloud Code Analysis not pass

Thank you very much for your review, I will complete the coverage of UT later

**Comment by yangyichao-mango** [comment]
+1，

But can you list any benchmarks about this improvement?

**Comment by CalvinKirs** [comment]
> +1，
> 
> But can you list any benchmarks about this improvement?

Thank you very much for your review, but about this issue, I think you can refer to this article, https://stackoverflow.com/questions/35568365/netty-epolleventloopgroup-vs-nioeventloopgroup-which-should-i-choose-on-centos ,The official maintainer of netty also recommends this. In addition, this method is also used in other apache projects. In addition, my computer is macos, so there is no way to test and verify it.
for those that can reach a consensus, we may not need to conduct micro-benchmarks, what do you think?

**Pull request merged**
