### PR TITLE
[Fix][API] Log dependency package conflict

### PR DESCRIPTION
**Pull request by hailin0**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

Fix log dependency package conflict (slf4j-log4j12、logback)

## Brief change log

Add exclusion for slf4j-log4j12

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by hailin0** [comment]
@qiaozhanwei

**Review by CalvinKirs — APPROVED** [review]
+1

**Comment by hailin0** [comment]
@dailidong Waiting for request to merged

**Review by dailidong — APPROVED** [review]
+1
good job

**Comment by dailidong** [comment]
thanks for your first contribution, looking forward for your deep participation, please contact me(wechat: 510570367 or mail: dailidong66@gmail.com), when added, please tell me your github id, thx

**Pull request merged**
