### PR TITLE
[Improvement][ui] Refactored dag formatting logic

### PR DESCRIPTION
**Pull request by elonlo**
## What is the purpose of the pull request

The frontend introduces the dagre library, and uses the layered graph drawing algorithm to calculate the position of each task node

## Brief change log

  - *Add dagre:0.8.5 to package.json*
  - *Add dagre info to LICENSE file*
  - *Add LICENSE-dagre new file*
  - *Modify dag.js reformat logic*

## Verify this pull request

before
image

after
image

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by break60** [comment]
Synchronize the remote branch code, thank you

**Review by break60 — APPROVED** [review]
+1

**Review by yangyichao-mango — APPROVED** [review]
LGTM.

**Review by lgcareer — APPROVED** [review]
The MIT license is OK. +1

**Pull request merged**
