### PR TITLE
[Feature-3222][datasource] Store password in ciphertext instead 

### PR DESCRIPTION
**Pull request by BoYiZhang**
Store password in ciphertext instead

Encryption / decryption using Base64

and add a switch to "encrypt or not"

No encryption by default

```
common.properties

datasource.encryption.enable=false
datasource.encryption.salt=!@#$%^&*


```

issues: #3222

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Hi,
Maybe we should also add the datasource ciphertext upgrader for old version and make it be compatible with the old version.

**Comment by BoYiZhang** [comment]
> Hi,
> Maybe we should also add the datasource ciphertext upgrader for old version and make it be compatible with the old version.

There is uncertainty in this

I think we can add a switch to "encrypt or not"

No encryption by default

It is up to the user to decide whether to enable it
What's your opinion?

**Comment by yangyichao-mango** [comment]
Hi,
I think we need to consider a scenario: what if the user replaced salt. Will it be decode rightly?
Or maybe we do not need to think about this scenario?

**Comment by chuyang-zl** [comment]
In which version will this change plan be released?
请问这个改动计划要在哪个版本中发布？

**Pull request merged**
