### PR TITLE
add job history to judge application status/2625

### PR DESCRIPTION
**Pull request by itbasketplayer**
## What is the purpose of the pull request
add job history status url to judge application status, when application number threshold is reached(default 10000,maybe it was set to 1000).
you can see issue #2625

### CODE REVIEW

**Comment by itbasketplayer** [comment]
image
this is not my change file :)

**Comment by dailidong** [comment]
could you submit this PR to dev-1.3.0,  we will fix bug on the dev-1.3.0 first

when published 1.3.0, will have more energy for reviewing the PR on the dev

**Comment by dailidong** [comment]
could you submit a same PR to dev-1.3.0 which is used for publishing 1.3.0 version

**Comment by itbasketplayer** [comment]
ok, but i can't pull/push with github at home because of network. I will finish it next Monday.

**Pull request merged**
