### PR TITLE
[FIX][UI]add button disabeld when isDetails

### PR DESCRIPTION
**Pull request by geosmart**
with ONLINE process definition Add button should disabeld for readOnly

### CODE REVIEW

**Comment by break60** [comment]
Is the save button in the gray toolbar more friendly

**Comment by geosmart** [comment]
> Is the save button in the gray toolbar more friendly

after click `save` ,user have to config something before click `add` 
image

**Comment by break60** [comment]
You add this graying out for the work that is already online. The backend of the online workflow is checked. If you are only for the online workflow, you can prevent the user from clicking the save button and restrict the user from adding it. Can’t add some changes

**Comment by geosmart** [comment]
> You add this graying out for the work that is already online. The backend of the online workflow is checked. If you are only for the online workflow, you can prevent the user from clicking the save button and restrict the user from adding it. Can’t add some changes

but if disabled the `save` button , i can't check the config[tenant,alert,timeout]info in the popout dialog,
so I just graying out the `add` button to avoid unnecessary click

**Comment by break60** [comment]
> but if disabled the `save` button , i can't check the config[tenant,alert,timeout]info in the popout dialog,
> so I just graying out the `add` button to avoid unnecessary click

If the user needs to see the configuration information inside, it is also possible

**Review by break60 — APPROVED** [review]
+1

**Review by qiaozhanwei — APPROVED** [review]
+1

**Pull request merged**
