### PR TITLE
 [FIXBUG][common]fix yarn applications status cause NPE(#3645)

### LINKED ISSUE #3645: [Bug][worker]  get yarn applications status from yarn server,http code return 404, get yarn applications status cause NullPointerException
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
[ERROR] 2020-09-02 15:37:27.040 org.apache.dolphinscheduler.common.utils.HttpUtils:[70] - http get:404 response status code is not 200!
[ERROR] 2020-09-02 15:37:27.043  - [taskAppId=TASK-5-185-263]:[388] - yarn applications: [application_1598594304061_22447]  status failed
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.common.utils.HadoopUtils.getApplicationStatus(HadoopUtils.java:415)
        at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:374)
        at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
        at org.apache.dolphinscheduler.server.worker.task.AbstractYarnTask.handle(AbstractYarnTask.java:57)
        at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
**Which version of Dolphin Scheduler:**
 -[1.3.2]

### PR DESCRIPTION
**Pull request by 597365581**
[FIXBUG][common]fix yarn applications status cause NPE

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*(For example: This pull request adds checkstyle plugin.)*

## Brief change log

*(for example:)*
  - *Add maven-checkstyle-plugin to root pom.xml*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Review by 597365581 — COMMENTED** [review]
fix get yarn applications status from yarn server,http code return 404, get yarn applications status cause NullPointerException

**Review by 597365581 — COMMENTED** [review]
get yarn applications status from yarn server,http code return 404, get yarn applications status cause NullPointerException

**Comment by 597365581** [comment]
fix get yarn applications status from yarn server,http code return 404, get yarn applications status cause NullPointerException

**Comment by felix-thinkingdata** [comment]
Can you describe what happens when volatilization happens?

**Comment by felix-thinkingdata** [comment]
> Can you describe what happens when volatilization happens? There is a difference between getting a status return exception, such as 404, and a task running status failure.It's best to describe the situation in detail.

> 
> 什么情况下会发生？还有就是获取状态404和获取运行状态是失败的还是有区别的。最好详细描述下情况。

**Comment by 597365581** [comment]
> > Can you describe what happens when volatilization happens? There is a difference between getting a status return exception, such as 404, and a task running status failure.It's best to describe the situation in detail.
> 
> > 什么情况下会发生？还有就是获取状态404和获取运行状态是失败的还是有区别的。最好详细描述下情况。

1、yarn http request timeout。2、yarn url is incorrect and so no...

**Comment by 597365581** [comment]
> > > Can you describe what happens when volatilization happens? There is a difference between getting a status return exception, such as 404, and a task running status failure.It's best to describe the situation in detail.
> > 
> > 
> > > 什么情况下会发生？还有就是获取状态404和获取运行状态是失败的还是有区别的。最好详细描述下情况。
> 
> 1、yarn http request timeout。2、yarn url is incorrect  3、 two yarn cluster，yarn url config in disorder and so no...

**Comment by felix-thinkingdata** [comment]
> > > > Can you describe what happens when volatilization happens? There is a difference between getting a status return exception, such as 404, and a task running status failure.It's best to describe the situation in detail.
> > > 
> > > 
> > > > 什么情况下会发生？还有就是获取状态404和获取运行状态是失败的还是有区别的。最好详细描述下情况。
> > 
> > 
> > 1、yarn http request timeout。2、yarn url is incorrect  3、 two yarn cluster，yarn url config in disorder and so no...

Does this erase any specific exception information in the log?

这样会抹去在日志中的具体的异常信息吗？

**Review by felix-thinkingdata — APPROVED** [review]
Optimized exceptions when getting information over YARN HTTP. 

优化了，在通过yarn http获取信息时的异常情况。

good job

**Comment by 597365581** [comment]
> Optimized exceptions when getting information over YARN HTTP.
> 
> 优化了，在通过yarn http获取信息时的异常情况。
> 
> good job

ok，can merge？

**Comment by felix-thinkingdata** [comment]
> ok，can merge？

Wait for others to review.I have no authority to merge

**Review by CalvinKirs — COMMENTED** [review]
+1
but，multiple if nesting does not seem intuitive enough, if it can be modified, it would be better。

**Comment by CalvinKirs** [comment]
please change the pr title to [FIXBUG][common]fix yarn applications status cause NPE

**Review by yangyichao-mango — APPROVED** [review]
LGTM

**Comment by felix-thinkingdata** [comment]
please change the pr title to [FIXBUG][common]fix yarn applications status cause NPE

按照要求改下标题。

**Comment by 597365581** [comment]
@felix-thinkingdata  ok, title has changed

**Review by qiaozhanwei — APPROVED** [review]
+1

**Pull request merged**
