### PR TITLE
[Fix-3233][api-server] Fix the bug when compile the code in Java9 env

### LINKED ISSUE #3233: [Bug][api-server] ClassCastException: AppClassLoader cannot be cast to class java.net.URLClassLoader
*For better global communication, please give priority to using English description, thx! *

**Which version of Dolphin Scheduler:**
1.3.1

**Describe the bug**
Just started the api-server, logs show as follows:

```
[WARN] 2020-07-17 10:17:17.231 org.eclipse.jetty.server.handler.ContextHandler.application:[2355] - unavailable
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:174)
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:429)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:221)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:142)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:36)
```

I found [an explaination on stackoverflow][1]. It shows that JDK 9 has a breaking change here.

[1]: https://stackoverflow.com/questions/39739075/hive-shell-not-loading/41637409#41637409

**Requirement or improvement**
Please fix this to make DS compatible with modern JDK. Thanks!

### PR DESCRIPTION
**Pull request by c-f-cooper**
this close #3233 

The root cause of this problem is that we have introduced jsp-2.1, but jsp-2.1 is not compatible with Java 9 (it is no longer maintained), so we must remove jsp-2.1. This work is necessary. After this PR is merged, we need to test again to see whether the api-server log can be started normally after debugging is turned on. (It was for this reason that jsp-2.1 was introduced)

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
delete it(release-docs/licenses/LICENSE-jsp-api-2.1-6.1.14.txt)

**Comment by c-f-cooper** [comment]
> delete it(release-docs/licenses/LICENSE-jsp-api-2.1-6.1.14.txt)

It does not take effect

**Comment by CalvinKirs** [comment]
Great job. The root cause of this problem is that we have introduced jsp-2.1, but jsp-2.1 is not compatible with Java 9 (it is no longer maintained), so we must remove jsp-2.1. This work is necessary. After this PR is merged, we need to test again to see whether the api-server log can be started normally after debugging is turned on. (It was for this reason that jsp-2.1 was introduced) @lgcareer

**Review by CalvinKirs — APPROVED** [review]
looks good to me

**Review by lgcareer — APPROVED** [review]
+1

**Comment by darrkz** [comment]
I user 1.3.6 and openjdk, still show the same errors

**Comment by davidzollo** [comment]
> I user 1.3.6 and openjdk, still show the same errors

you can create an new issue to describe the detailed error

**Comment by CalvinKirs** [comment]
This issue was not merged into the release branch. Does it need to be considered for merging into 1.3.7? (full testing may be needed) @dailidong

**Comment by davidzollo** [comment]
> This issue was not merged into the release branch. Does it need to be considered for merging into 1.3.7? (full testing may be needed) @dailidong

if it is a bug , please merge it into the coming release version

**Comment by CalvinKirs** [comment]
> > This issue was not merged into the release branch. Does it need to be considered for merging into 1.3.7? (full testing may be needed) @dailidong
> 
> if it is a bug , please merge it into the coming release version

This is not a bug, what we need to decide is whether to adapt to Java9.

**Comment by xied75** [comment]
> > > This issue was not merged into the release branch. Does it need to be considered for merging into 1.3.7? (full testing may be needed) @dailidong
> > 
> > 
> > if it is a bug , please merge it into the coming release version
> 
> This is not a bug, what we need to decide is whether to adapt to Java9.

If you stated the environment to run/test/debug, i.e. you told people it only works with Java8, then it's a feature.

If on the other hand you let people find this by themselves, as a surprise, then it's a bug.

**Pull request merged**
