### PR TITLE
support ali nail(ding talk) , issue:2458

### PR DESCRIPTION
**Pull request by stanfen**
## What is the purpose of the pull request

*develop issue #2458 : support send msg to ali nail(ding talk) based on ding talk advanced extension: ding talk bots.*

- Group bots can aggregate information from third-party services (like ds) into a group chat, enabling automated information synchronization.
- enable the function require Webhook configuration. the offical link: [enable ding talk](<https://ding-doc.dingtalk.com/doc#/serverapi3/pghqkk>)

## Brief change log

- *modify alert  module*
- *add ding talk msg convert class DingTalkMsgFormatter*
- *add DingTalkUtils to execute message sending*
- *modify alert.properties for config proxy, keyword and webhook etc*

## Verify this pull request

*(Please pick either of the following options)*

This change added tests and can be verified as follows:

- *Added test case: executing mesage sending but ingore because of lack of configration*
- *Added DingTalkMsgFormatter tested*
- *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by hgaol** [comment]
Is it suitable to use plugin way to support this alert method?

**Comment by dailidong** [comment]
please add  DingTalkUtilsTest to project root pom.xml, like this:
image

**Comment by stanfen** [comment]
anyone can review the pr. 
the offical link tell us how to use.
https://ding-doc.dingtalk.com/doc#/serverapi3/iydd5h

**Comment by dailidong** [comment]
good job, 
I want to know how to make "the dingtalk plugin", if there is a simple doc will be better, how do you think?

**Comment by stanfen** [comment]
> good job,
> I want to know how to make "the dingtalk plugin", if there is a simple doc will be better, how do you think?

PR using ding talk chat bots to send messages, implement notifications and alerts.To enable the plugin what we need is to complete two steps.
- *first, set ding talk chat bots*
It easy to do that in ding talk PC client. [Group] -> [Settings] ->[Group Assistant] -> [Add bots]，and then following the guidelines to set up. Please do remember webhook and keyword, can be set in the DS alert.properties.
- *second, para setting in alert.properties*
 it includes two kinds of parameters： required and optional parameters
1. required parameters
dingtalk.isEnable//the switch to enable feature or not
dingtalk.webhook //URL to send message, getting in first step
dingtalk.keyword // keyword for filtering message, getting in first step
2. optional parameters
if requiring a proxy server to access the network, please setting the following:
dingtalk.proxy=
dingtalk.port=
dingtalk.user=
dingtalk.password=
dingtalk.isEnableProxy=enable

中文描述：
PR利用钉钉群组接收自定义机器人消息机制进行开发。激活功能需要进行2步骤操作：
- *设置钉钉群自定义机器人*
官方提供说明 [官方设置机器人方法](https://www.dingtalk.com/qidian/help-detail-20781541.html)
设置完成后，保存钉钉提供webhook 和关键字等信息。ds需要这2个参数。
- *ds中配置的参数在文件alert.properties*：
1.必须参数：
dingtalk.isEnable//是否开启钉钉消息推送
dingtalk.webhook //钉钉群接收消息。需要通过PC客户端设置，获取。
dingtalk.keyword//钉钉群支持消息过滤包括：关键字过滤，即只接收包含关键字消息。
2.非必须参数：*需要代理才能访问网络时，可定义代理参数*
dingtalk.proxy=
dingtalk.port=
dingtalk.user=
dingtalk.password=
dingtalk.isEnableProxy=enable

**Comment by hgaol** [comment]
Hmm.. just answer lidong's question. This is not a plugin, it was coded in Alert service. But currently, there is no entry for DS to choose alert way in the frontend portal, I think this may be enough. Maybe when plugin way is approved and implemented, someone or me can refactor some code to plugin.

For alert plugin doc, I created a PR, which hasn't been merged, you can refer to that PR(hello-world plugin demo).

**Comment by BackFire** [comment]
> > good job,
> > I want to know how to make "the dingtalk plugin", if there is a simple doc will be better, how do you think?
> 
> PR using ding talk chat bots to send messages, implement notifications and alerts.To enable the plugin what we need is to complete two steps.
> 
> * _first, set ding talk chat bots_
>   It easy to do that in ding talk PC client. [Group] -> [Settings] ->[Group Assistant] -> [Add bots]，and then following the guidelines to set up. Please do remember webhook and keyword, can be set in the DS alert.properties.
> * _second, para setting in alert.properties_
>   it includes two kinds of parameters： required and optional parameters
> 
> 1. required parameters
>    dingtalk.isEnable//the switch to enable feature or not
>    dingtalk.webhook //URL to send message, getting in first step
>    dingtalk.keyword // keyword for filtering message, getting in first step
> 2. optional parameters
>    if requiring a proxy server to access the network, please setting the following:
>    dingtalk.proxy=
>    dingtalk.port=
>    dingtalk.user=
>    dingtalk.password=
>    dingtalk.isEnableProxy=true
> 
> 中文描述：
> PR利用钉钉群组接收自定义机器人消息机制进行开发。激活功能需要进行2步骤操作：
> 
> * _设置钉钉群自定义机器人_
>   官方提供说明 [官方设置机器人方法](https://www.dingtalk.com/qidian/help-detail-20781541.html)
>   设置完成后，保存钉钉提供webhook 和关键字等信息。ds需要这2个参数。
> * _ds中配置的参数在文件alert.properties_：
>   1.必须参数：
>   dingtalk.isEnable//是否开启钉钉消息推送
>   dingtalk.webhook //钉钉群接收消息。需要通过PC客户端设置，获取。
>   dingtalk.keyword//钉钉群支持消息过滤包括：关键字过滤，即只接收包含关键字消息。
>   2.非必须参数：_需要代理才能访问网络时，可定义代理参数_
>   dingtalk.proxy=
>   dingtalk.port=
>   dingtalk.user=
>   dingtalk.password=
>   dingtalk.isEnableProxy=true

按照这个配置完成之后，如何在工作流中使用钉钉告警？我用的版本是dev分支编译的

**Pull request merged**
