### PR TITLE
fix bug #4125

### LINKED ISSUE #4125: [Bug][worker]command body parseObject error
code:

class: DBTaskResponseProcessor
method: process
line: JSONUtils.parseObject(command.getBody(),DBTaskResponseCommand.class);
runing data: {"taskInstanceId":8,"status":7}

error details:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.dolphinscheduler.remote.command.DBTaskResponseCommand` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"taskInstanceId":6,"status":7}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004) ~[jackson-databind-2.9.8.jar:2.9.8]
	at org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(JSONUtils.java:124) [classes/:na]
	at org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(JSONUtils.java:144) [classes/:na]
	at org.apache.dolphinscheduler.server.worker.processor.DBTaskResponseProcessor.process(DBTaskResponseProcessor.java:45) [classes/:na]
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler$1.run(NettyServerHandler.java:128) [classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

### PR DESCRIPTION
**Pull request by chengpeng2015**
fix  #4125 , DBTaskAckCommand and DBTaskResponseCommand add construction method！

### CODE REVIEW

**Comment by CalvinKirs** [comment]
code style error, you can refer to the official document, he will tell you how to configure the plug-in to complete the work https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html
btw,It is best to provide ut for your change.

**Comment by dailidong** [comment]
thanks for your first contribution, code style should keep consistence, please referer 
image

**Comment by dailidong** [comment]
please contact me (lidongdai@apache.org or wechat: 510570367) , please tell me your github id when added, thx

**Review by chengpeng2015 — COMMENTED** [review]
code style

**Review by dailidong — APPROVED** [review]
good job
+1

**Pull request merged**
