### PR TITLE
[test-2559][e2e] test data configure isolation 

### PR DESCRIPTION
**Pull request by xingchun-chen**
#2559 test data configure isolation

### CODE REVIEW

**Comment by xingchun-chen** [comment]
@yangyichao-mango Please look at the code styte error of java.io.* ,  What needs to be changed
image

**Comment by yangyichao-mango** [comment]
> @yangyichao-mango Please look at the code styte error of java.io.* ,  What needs to be changed
> 
> image
> 
> 

It's not recommend to use import a.*, we should use the specific class like import a.B.

**Comment by xingchun-chen** [comment]
Use the following class to report the same error
import java.io.IOException;
import java.io.InputStream;

**Review by qiaozhanwei — APPROVED** [review]
+1

**Pull request merged**
