### PR TITLE
[Fix-3707][ui] The batch delete function in the workflow definition and workflow instance pages cannot be canceled if selected

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request
 #3707 
Workflow definition and batch deletion of workflow instance pages
1.Click the batch delete button, the cancel click in the prompt box has no effect
2.After the batch delete is successful, the batch delete button is displayed in a clickable state. Normally, it cannot be clicked. You should delete the records first before clicking the batch delete.

## Brief change log
definition list.vue
instance list.vue

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.*

---

Snipaste_2020-09-09_19-41-24

Snipaste_2020-09-09_19-46-30

工作流定义和工作流实例页面批量删除功能
1.点击批量删除按钮，提示框内的取消点击没有效果
2.批量删除成功后，批量删除按钮展示还是可点击状态，正常是不可以点击的，应该先删除记录，才可以点击批量删除。

### CODE REVIEW

**Review by break60 — APPROVED** [review]
+1

**Comment by yangyichao-mango** [comment]
Please change title to `[Fix-3707][ui] The batch delete function in the workflow definition and workflow instance pages cannot be canceled if selected`

**Review by yangyichao-mango — APPROVED** [review]
LGTM

**Comment by zhuangchong** [comment]
@xingchun-chen done. Please help to review.

**Review by xingchun-chen — APPROVED** [review]
+1

**Pull request merged**
