### PR TITLE
[Fix][UI] Alert-server warningInstance title support internationalization.

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request

image

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by break60** [comment]
image
There is no content change in these two files, so don't mention it.

**Comment by zhuangchong** [comment]
@break60 the two file change 'pulginInstance' to 'pluginInstance'

image

**Review by break60 — APPROVED** [review]
+1

**Review by xingchun-chen — APPROVED** [review]
+1

**Pull request merged**
