### PR TITLE
[Feature]add "shell task" support for varpool

### PR DESCRIPTION
**Pull request by guyinyou**
Signed-off-by: 古崟佑

The function of varpool is implemented in <https://github.com/apache/incubator-dolphinscheduler/pull/3659>, but only Python type tasks are supported. Shell type tasks are supported in this pr

-----------------------------------------------------------------------------------------------------------------------------

<https://github.com/apache/incubator-dolphinscheduler/pull/3659>中实现了Varpool的功能，但是只支持python类型的任务，在这次pr中增加了对shell类型任务的支持

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Hi, please resolve the conflict.. thx

**Comment by gabrywu** [comment]
@guyinyou  Please resolve the conflicts

**Comment by guyinyou** [comment]
I'm sorry to reply now, because I learned from my tutor that the function of "varpool" needs to be re implemented with a new scheme, so there is no need for subsequent modification for the time being

**Comment by CalvinKirs** [comment]
If there is a new design plan in the future, you can send an email to discuss with us, and I will temporarily close this PR.

**Pull request closed without merging**
