### PR TITLE
[refactor][server-test] refactor RoundRobinHostManagerTest

### PR DESCRIPTION
**Pull request by CalvinKirs**
refactor RoundRobinHostManagerTest

#3512

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@dailidong @qiaozhanwei  Could you please review this for me?

**Review by qiaozhanwei — APPROVED** [review]
+1

**Comment by CalvinKirs** [comment]
> please resolved conflicts
> +1

I have completed the changes, please check

**Review by dailidong — APPROVED** [review]
+1
great job for DS

**Pull request merged**
