### PR TITLE
Refactor BaseDataSource and unified handling of JDBC resource releases.

### PR DESCRIPTION
**Pull request by yh2388**
* Refactor BaseDataSource.isConnectable().

* Refactor BaseDataSource.getJdbcUrl().

* Unified handling of JDBC resource releases.

### CODE REVIEW

**Comment by dailidong** [comment]
first please solve Conflicting files locally

**Comment by yh2388** [comment]
> first please solve Conflicting files locally

Solved!

**Comment by dailidong** [comment]
concise code

**Comment by dailidong** [comment]
@xingchun-chen ，xingchun，please remember test the new code later,  this pr changes a lot

**Comment by xingchun-chen** [comment]
OK，i will test it!


陈兴春
长沙测试工程师
+8615801675490
chenxingchun@analysys.com.cn
长沙公司地址：长沙市岳麓区尖山路39号中电软件园总部三楼，电话：0731-83522068
北京公司地址：北京市朝阳区酒仙桥路10号恒通商务园B12C座三层
易观官网：http://www.analysys.cn/
客服电话：4006-010-230 / 4006-010-231
-----------------------------------
  北京 ｜ 上海 ｜ 深圳 ｜ 成都 ｜ 长沙




原始邮件
发件人:dailidongnotifications@github.com
收件人:apache/incubator-dolphinschedulerincubator-dolphinscheduler@noreply.github.com
抄送:xingchun-chenchenxingchun@analysys.com.cn; Mentionmention@noreply.github.com
发送时间:2020年3月26日(周四) 23:23
主题:Re: [apache/incubator-dolphinscheduler] Refactor BaseDataSource andunified handling of JDBC resource releases. (#2184)


@xingchun-chen ，xingchun，please remember test the new code later, this pr changes a lot

**Pull request merged**
