### PR TITLE
[Fix-3607][ui] Fix version control online process definition editable

### PR DESCRIPTION
**Pull request by yangyichao-mango**
## What is the purpose of the pull request

*Fix version control online process definition editable* (#3607 )

## Brief change log

  - *`dag.vue` pass the releaseState and `version.vue` got the state and judge*

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
@chenxingchun @break60 @geosmart Please help to review.

**Review by break60 — APPROVED** [review]
+1

**Review by xingchun-chen — APPROVED** [review]
+1

**Comment by geosmart** [comment]
+1

**Pull request merged**
