### PR TITLE
[Improvement][Alert]Alert problem repair and optimization

### PR DESCRIPTION
**Pull request by CalvinKirs**
* Fix mybatis-plus empty value update problem

* When deleting the alert-plugin instance, determine whether there is an alert group association

* When the alert is executed, if the alarm group is not bound to the alert plug-in, the alert status is updated to fail.

### CODE REVIEW

**Comment by zhuangchong** [comment]
+1

**Review by gaojun2048 — APPROVED** [review]
+1

**Comment by gaojun2048** [comment]
Test coverage ?

**Review by gaojun2048 — APPROVED** [review]
+1

**Pull request merged**
