### PR TITLE
[Fix] fix bug #3487 Create folder duplicate name under multithreading 

### PR DESCRIPTION
**Pull request by muzhongjiang**
## What is the purpose of the pull request
image

**sql test:**

image

### CODE REVIEW

**Comment by muzhongjiang** [comment]
@yangyichao-mango   @lgcareer

**Comment by yangyichao-mango** [comment]
Please resolve ut test error.

**Review by lgcareer — APPROVED** [review]
+1

**Review by yangyichao-mango — APPROVED** [review]
LGTM

**Comment by lgcareer** [comment]
linked issue #3487

**Pull request merged**
