### PR TITLE
[Future#3253][Display website title favicon.ico

### PR DESCRIPTION
**Pull request by kevinsun2010**
## What is the purpose of the pull request
#3253 

## Brief change log
-add favicon.ico file  in path dolphinscheduler-api\src\main\resources\resources\favicon.ico

## Verify this pull request
The test results dispaly：

### CODE REVIEW

**Comment by break60** [comment]
The website now displays ico, are you using nginx deployment?

**Comment by kevinsun2010** [comment]
> The website now displays ico, are you using nginx deployment?

not use nginx deployment。 
The official demo is not display ico and dev branch is not display  too.
official demo: http://106.75.43.194:8888/dolphinscheduler/ui/view/login/index.html
please confirm it .

**Comment by break60** [comment]
> not use nginx deployment。
> The official demo is not display ico and dev branch is not display too.
> official demo: http://106.75.43.194:8888/dolphinscheduler/ui/view/login/index.html
> please confirm it .

The code on the demo has not been updated for a long time, the dev code has fixed this problem

**Comment by kevinsun2010** [comment]
> The website now displays ico, are you using nginx deployment?

i find dolphinscheduler-ui/src/images/favicon.ico file .

**Comment by kevinsun2010** [comment]
> > not use nginx deployment。
> > The official demo is not display ico and dev branch is not display too.
> > official demo: http://106.75.43.194:8888/dolphinscheduler/ui/view/login/index.html
> > please confirm it .
> 
> The code on the demo has not been updated for a long time, the dev code has fixed this problem

i see .i find  the file  "i find dolphinscheduler-ui/src/images/favicon.ico "
how to deployment  to display ?

**Comment by break60** [comment]
Now the file is in the root directory of dolphinscheduler-ui in png format

**Comment by kevinsun2010** [comment]
> > not use nginx deployment。
> > The official demo is not display ico and dev branch is not display too.
> > official demo: http://106.75.43.194:8888/dolphinscheduler/ui/view/login/index.html
> > please confirm it .
> 
> The code on the demo has not been updated for a long time, the dev code has fixed this problem


> Now the file is in the root directory of dolphinscheduler-ui in png format
i konw . update dev branch code can display .  thanks .

**Pull request closed without merging**
