### PR TITLE
[bugfix] "getNotifyGroupList"  cache bug #3179

### PR DESCRIPTION
**Pull request by muzhongjiang**
## Verify this pull request

1、create:

image

2、get all  notify group ：
image

### CODE REVIEW

**Comment by qiaozhanwei** [comment]
@break60 please review . Thx

**Comment by muzhongjiang** [comment]
> why compile not running . please renew commit . Thx

image

**Comment by break60** [comment]
> > why compile not running . please renew commit . Thx
> 
> image

'compiled successfully', isn't this already compiled successfully?

**Comment by qiaozhanwei** [comment]
> > why compile not running . please renew commit . Thx
> 
> image
> 
> @qiaozhanwei compiled successfully

Some checks haven’t completed yet and SonarCloud Code Analysis  not running . please use retry commit . Thx

**Pull request merged**
