### PR TITLE
feature: Add user state #1923

### PR DESCRIPTION
**Pull request by Rubik-W**
Please see #1923 for details.

Before merge, need to execute sql script.

### CODE REVIEW

**Comment by dailidong** [comment]
find Conflicting files,please solve locally

**Comment by Rubik-W** [comment]
fixed conflict

**Comment by Rubik-W** [comment]
Because The t_ds_user table add "state" column, UT is failed.
Need to execute the sql script first.

**Comment by break60** [comment]
Please solve ut

**Comment by Rubik-W** [comment]
@lgcareer  Please review this PR.

**Comment by break60** [comment]
frontend+1

**Comment by Rubik-W** [comment]
Detailed discussion process:
https://lists.apache.org/thread.html/re2f0adfcae972ba7ccf5e8f131e88b8f9f610b71c2029b61d0cfa185%40%3Cdev.dolphinscheduler.apache.org%3E

**Pull request merged**
