### PR TITLE
[Feature-3985][Datax] Datax supports setting up running memory

### LINKED ISSUE #3985: [Feature][Datax] Datax supports setting up running memory
DataX default memory is 1g, when the amount of data is large, memory will not be enough

So you need to support setting runtime JVM memory

image

### PR DESCRIPTION
**Pull request by BoYiZhang**
Datax supports setting up running memory
this close #3985

### CODE REVIEW

**Comment by break60** [comment]
image
Take a look at these two files. Is the coverage rate insufficient?

**Comment by BoYiZhang** [comment]
> image
> Take a look at these two files. Is the coverage rate insufficient?

I mainly added a method and wrote test cases

Why is the coverage rate 0.0%

image

**Review by break60 — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
