### PR TITLE
Improve the user experience in the task definition page, define the architecture and implement http.vue

### PR DESCRIPTION
**Pull request by nauu**
## What is the purpose of the pull request

This pull request will finish the subtask architecture and http in  #1675. 

It will improve the user experience in the task definition page.

When we set up the task param, it can automatically cache the input. When we change task instance or cancel the task window without reloading the browser, the previous value will fillback after we open the task window again.

## Brief change log

  - *Edit state.js*
  - *Edit mutations.js*
  - *Edit dag.vue*
  - *Edit formModel.vue*
  - *Edit http.vue*

## Verify this pull request

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by break60** [comment]
image
jquery has been globally referenced, no need to duplicate references

**Comment by nauu** [comment]
@break60 i had been remove jquery. 
I didn't  format  the code, I don't know why the format changes.

**Comment by nauu** [comment]
@break60 the format  has changed as before

**Comment by break60** [comment]
+1

**Pull request merged**
