### PR TITLE
[Improvement][common] Add UnsupportedOperationException for utils construct

### PR DESCRIPTION
**Pull request by yangyichao-mango**
## What is the purpose of the pull request

*Add UnsupportedOperationException for utils construct to avoid the construct of utils and improvement the robust of code*

## Brief change log

  - *All utils in common module, add the UnsupportedOperationException in every utils construct*

### CODE REVIEW

**Review by qiaozhanwei — APPROVED** [review]
please resolve conflicts 
+1

**Comment by CalvinKirs** [comment]
please resolve conflicts

**Comment by yangyichao-mango** [comment]
@CalvinKirs @qiaozhanwei done.

**Review by CalvinKirs — APPROVED** [review]
+1

**Review by lgcareer — APPROVED** [review]
+1

**Pull request merged**
