### PR TITLE
add repace time when run history job and batch complement job ,not current time

### PR DESCRIPTION
**Pull request by rusonding**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*(For example: This pull request adds checkstyle plugin.)*

## Brief change log

*(for example:)*
  - *Add maven-checkstyle-plugin to root pom.xml*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by lenboo** [comment]
please submit an issue  about this.

**Comment by dailidong** [comment]
as the issue : #2208 said,  maybe it not a problem,  if you have any question, please come on

By the way , Thanks for your first contribtuion, Looking forward to your next , haha

**Comment by dailidong** [comment]
for now, I knew what you said

good job

**Comment by dailidong** [comment]
for now , We hope the unit test coverage of new code to 30%, but because it's your first contribution. come on

**Pull request merged**
