### PR TITLE
[Feature]modify some cases from rockxsj:Feature-presto to add presto datasource support 

### PR DESCRIPTION
**Pull request by dengc367**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

I have merged the presto feature from [[Feature]add presto datasource support](https://github.com/apache/incubator-dolphinscheduler/pull/3308) and modify some files to fix two bugs in that presto feature branch.

## Brief change log

         new file:   dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/PrestoDataSource.java
        modified:   .gitignore
        modified:   dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
        modified:   dolphinscheduler-common/pom.xml
        modified:   dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
        modified:   dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/DbType.java
        modified:   dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/BaseDataSource.java
        modified:   dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/DataSourceFactory.java
        modified:   dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
        modified:   dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
        modified:   dolphinscheduler-ui/src/js/conf/home/store/datasource/actions.js
        modified:   pom.xml

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by dengc367** [comment]
this modified feature was tested in our online environment, so I am going to pull request it to feedback & contribute to the dolphinscheduler community. thanks @rockxsj to contribute the base code.

**Comment by dengc367** [comment]
who can merge this feature to the dev branch. thanks.

**Comment by dailidong** [comment]
Please solve conficting files locally, 
by the way, I have merged the PR #3308 first,  because we use squash merge,  can't see his PR submission if I directly merge this PR
last, thanks for your first contribution, if you need any help , please contact my wechat(510570367), when added , please tell me your github id, thx

**Comment by dengc367** [comment]
@dailidong I have solved the conflicting files, now. you can merge now. thank @rockxsj for the initial contribution.

**Comment by dailidong** [comment]
good job，thanks for your first contribution, please contact my wechat(510570367) , when added, please tell your github id, thx

**Pull request merged**
