### PR TITLE
[Improvement][DAO] druid The lower version is not compatible with LocalDateTime(DRUID 低版本不支持LocalDateTime)

### PR DESCRIPTION
**Pull request by felix-thinkingdata**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

druid The lower version is not compatible with LocalDateTime

https://github.com/alibaba/druid/issues/3490

https://github.com/alibaba/druid/issues/3170

### CODE REVIEW

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
good job,but there is a problem to pay attention to, you need to modify the version of druid.jar synchronously in known-dependencies.txt

**Comment by felix-thinkingdata** [comment]
> good job,but there is a problem to pay attention to, you need to modify the version of druid.jar synchronously in known-dependencies.txt

OK。Done

**Review by CalvinKirs — APPROVED** [review]
+1

**Review by yangyichao-mango — APPROVED** [review]
LGTM

**Review by dailidong — APPROVED** [review]
+1

**Pull request merged**
