### PR TITLE
[bugFix#3085]fix dag zoom

### PR DESCRIPTION
**Pull request by satcblue**
## What is the purpose of the pull request
FIX BUG #3085 

## Brief change log
jsPlumbHandle.js
dragZoom.js
util.js

## Attention:
It is important to note that dragging the canvas is not supported now! Despite this feature before, it didn't actually do much. About dragging the canvas, you can consider other ways to implement under this modification (it can play the effect of pulling the scroll bar)

### CODE REVIEW

**Comment by satcblue** [comment]
According to #3085 , i think the method of using jsplumb is not feasible. jsplumb toolkit version is a commercial version(LOL). 
I once implemented the function of dragging and dropping canvas, but its performance is not satisfactory. I will be very grateful If u can give me some suggestions.

**Comment by dailidong** [comment]
@break60 please review this PR

**Comment by dailidong** [comment]
good job,thanks for your first contribution.
if you need help, please send mail to dev@dolphinscheduler.apache.org or my wechat(510570367), when added, please tell me your github id, thx

**Comment by break60** [comment]
front end +1

**Comment by satcblue** [comment]
> good job,thanks for your first contribution.
> if you need help, please send mail to [dev@dolphinscheduler.apache.org](mailto:dev@dolphinscheduler.apache.org) or my wechat(510570367), when added, please tell me your github id, thx

THX! I am very happy to contribute to open source software. Thank you for leaving your contact information!

**Pull request merged**
