### PR TITLE
[Improvement][Code style] FIX SPELL WAITTING TO WAITING , etc.

### PR DESCRIPTION
**Pull request by felix-thinkingdata**
fix spell "WAITTING" to "WAITING"
"CMDPARAM_"   to  "CMD_PARAM_"
Add "@Override" annotations to the necessary methods

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Would it be better to change CMDPARAM to CMD_PARAM?

**Comment by felix-thinkingdata** [comment]
> Would it be better to change CMDPARAM to CMD_PARAM?

Yes, I'd better change this one, too

**Review by CalvinKirs — APPROVED** [review]
+1

**Comment by CalvinKirs** [comment]
Hi, I noticed that the UT coverage of this part of the code is insufficient, can you complete it?

**Comment by felix-thinkingdata** [comment]
> Hi, I noticed that the UT coverage of this part of the code is insufficient, can you complete it?



> Hi, I noticed that the UT coverage of this part of the code is insufficient, can you complete it?

Ok, Let me finish, UT supplement

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
