### PR TITLE
Adapting partial code(file name start with O) to the sonar cloud rule

### PR DESCRIPTION
**Pull request by gabrywu**

### CODE REVIEW

**Comment by xingchun-chen** [comment]
Please re-merge the code and submit

**Comment by gabrywu** [comment]
> Please re-merge the code and submit

done

**Comment by xingchun-chen** [comment]
Are you sure to rebase the dev code and push it again? there is only one commit in pr

**Comment by gabrywu** [comment]
> 
> 
> Are you sure to rebase the dev code and push it again? there is only one commit in pr

Yes.

**Comment by xingchun-chen** [comment]
e2e running code is not up to date, can you try to close this pr and push again?

**Pull request closed without merging**
