### PR TITLE
[Sqoop-Update]modify sqoop task param when upgrade ds to 1.3.4

### PR DESCRIPTION
**Pull request by Eights-Li**
## What is the purpose of the pull request

*1 add --target-dir param to deal with import mysql to hive using sql query failed*
*2 modify sqoop task param when ds < 1.3.4 upgrade to 1.3.4*
*3 fix sqoop task import mysql to hive the web no hive selector*

## Brief change log

  - *add --target-dir param to deal with import mysql to hive using sql query failed*
  - *modify sqoop task param when ds < 1.3.4 upgrade to 1.3.4*
  - *fix sqoop task import mysql to hive the web no hive selector*
## Verify this pull request
This change added tests and can be verified as follows:
  - *worker/task/SqoopTaskTest*

### CODE REVIEW

**Comment by lgcareer** [comment]
@Eights-Li I saw the ddl or dml under 1.3.4 is empty,so if 1.3.4 vresion didn't changed table schema or change table field values,so it's better not to create the 1.3.4_schema folder under sql/upgreade.

**Comment by Eights-Li** [comment]
> @Eights-Li I saw the ddl or dml under 1.3.4 is empty,so if 1.3.4 vresion didn't changed table schema or change table field values,so it's better not to create the 1.3.4_schema folder under sql/upgreade.

In ds-1.3.4, sqoop task meta data need to upgrade, when running upgrade code, need the schemaversion = 1.3.4, so I add the 1.3.4-schema dir in sql/update

**Comment by lgcareer** [comment]
> > @Eights-Li I saw the ddl or dml under 1.3.4 is empty,so if 1.3.4 vresion didn't changed table schema or change table field values,so it's better not to create the 1.3.4_schema folder under sql/upgreade.
> 
> In ds-1.3.4, sqoop task meta data need to upgrade, when running upgrade code, need the schemaversion = 1.3.4, so I add the 1.3.4-schema dir in sql/update

OK,Got it.

**Review by lgcareer — APPROVED** [review]
+1

**Comment by xingchun-chen** [comment]
+1

**Pull request merged**
