### PR TITLE
[Fix][api] Add queryProjectCreatedAndAuthorizedByUser function

### PR DESCRIPTION
**Pull request by zixi0825**
## What is the purpose of the pull request

*This pull request adds queryProjectCreatedAndAuthorizedByUser fuction*

When performing batch copy or move, you need to select the target projects. The purpose of this pr  is as follows:
- When the user is admin, all projects can be the target project
- When the user is an ordinary user, the projects he created and authorized can be  the target project

### CODE REVIEW

**Comment by dailidong** [comment]
please solve conflicting files locally, thx

**Review by CalvinKirs — APPROVED** [review]
looks good to me

**Review by dailidong — APPROVED** [review]
+1

**Comment by dailidong** [comment]
one PR need one corresponding issue, so please create an issue for PR next time

**Pull request merged**
