### PR TITLE
fix The create user is always loading when the queue does not select any value

### PR DESCRIPTION
**Pull request by samz406**
fix issue #2545

The create user is always loading when the queue does not select any value

### CODE REVIEW

**Comment by qiaozhanwei** [comment]
@break60

**Comment by break60** [comment]
frontend +1

**Comment by samz406** [comment]
@xingchun-chen  please review

**Comment by xingchun-chen** [comment]
I will test it

**Comment by xingchun-chen** [comment]
When creating a user, the queue value is not passed in the front end, and the queue in the database is also empty, but the user management is queried, and the queue is returned by the back end
 

image
image

image

**Comment by samz406** [comment]
i will check

**Pull request merged**
