### PR TITLE
[BUG-#4526][common]calculate cpu usage to support application running in container

### LINKED ISSUE #4526: [Bug][WorkerServer] worker server doesn't work fine in K8s
i  run a worker server in k8s,not change the worker server parms,sometime i run into the error in the picture,dispath do not find a suiteable worker to do the task.
截屏2021-01-20 下午8 44 42

### PR DESCRIPTION
**Pull request by crazycarry**
when i user worker in container,the method just return hosts load,not the container load. i try to get the data from  OperatingSystemMXBean,if it fails,just like before. in container env,you should make parms in worker. max.cpuload.avg bigger than cpucores *2, to avoid master do not dispatch task to the worker

this close #4526

### CODE REVIEW

**Comment by CalvinKirs** [comment]
hi, great contribution, but you need to resolve conflicting files first

**Review by dailidong — APPROVED** [review]
good job
+1

**Comment by dailidong** [comment]
> hi, great contribution, but you need to resolve conflicting files first

this is @crazycarry 's first contribution，I solved the conflict file

**Comment by dailidong** [comment]
thanks for your first contribution, looking forward to your deep participation

**Comment by CalvinKirs** [comment]
**notice**:see #5198

**Pull request merged**
