### PR TITLE
[Improvement-3717][server] ProcedureTask package naming modification, processdure changed to procedure. 

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request
#3717
ProcedureTask package naming modification, processdure changed to procedure.

## Brief change log

/task/processdure/ProcedureTask.java → .../worker/task/procedure/ProcedureTask.java

## Verify this pull request

This pull request is code cleanup without any test coverage.

---
##拉取请求的目的是什么

ProcedureTask程序包的命名修改，processdure 更改为 procedure

##简要更改日志

/task/processdure/ProcedureTask.java→... / worker / task / procedure / ProcedureTask.java

### CODE REVIEW

**Comment by zhuangchong** [comment]
The ProcedureTaskTest test class needs to connect to the database, which can be done locally, but how to connect to the Sonar check if the PR is submitted?

---
ProcedureTaskTest 测试类里面需要连接数据库，本地可以，但是PR提交，Sonar 检查如何去连接？

**Comment by zhuangchong** [comment]
@dailidong @qiaozhanwei

**Review by yangyichao-mango — APPROVED** [review]

**Comment by zhuangchong** [comment]
@dailidong @qiaozhanwei  

This PR is just to solve the naming modification of the ProcedureTask package. The processdure is changed to procedure. When the test class is added,it is found DriverManager.getConnection() can't mock.So SonarCloud Code Analysis checks were not successful.

---
此PR只是解决ProcedureTask程序包的命名修改，processdure 更改为 procedure，在添加测试类时，发现
DriverManager.getConnection() 不能模拟.所以SonarCloud Code Analysis 检查不成功

**Comment by CalvinKirs** [comment]
Failed condition 14.2% 14.2% Coverage on New Code (is less than 33%)
Failed condition 3.8% Condition Coverage on New Code (is less than 33%)



> @dailidong @qiaozhanwei
> 
> This PR is just to solve the naming modification of the ProcedureTask package. The processdure is changed to procedure. When the test class is added,it is found DriverManager.getConnection() can't mock.So SonarCloud Code Analysis checks were not successful.
> 
> 此PR只是解决ProcedureTask程序包的命名修改，processdure 更改为 procedure，在添加测试类时，发现
> DriverManager.getConnection() 不能模拟.所以SonarCloud Code Analysis 检查不成功

You can simulate the database connection in the form of mock. In addition, the reason why sonar fails is that the coverage rate of single test is not enough, and at the same time, there is too much redundant code.

**Comment by Jave-Chen** [comment]
For 0.0% Coverage , I created a topic to ask the sonarcloud community, you can follow it.

https://community.sonarsource.com/t/0-coverage-on-github-pr/34528

**Comment by zhuangchong** [comment]
done. #4094

**Pull request closed without merging**
