### PR TITLE
[Improvement] Refactor code to support distributed tracing

### PR DESCRIPTION
**Pull request by hailin0**
## What is the purpose of the pull request

- Refactor code to support tracing 

## Brief change log

  - Extension network protocol, support context and version
  - Extension master asynchronous queue support context
  - Extract scan task method from MasterSchedulerService for tracing

## Verify this pull request

This change added tests and can be verified as follows:
  - *Update Test case to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by hailin0** [comment]
@dailidong please check.

**Comment by chengshiwen** [comment]
@hailin0 Maybe you should fix the `Unit Test / Check code style` at first.

**Comment by CalvinKirs** [comment]
You can refer to: https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

**Comment by hailin0** [comment]
> @hailin0 Maybe you should fix the `Unit Test / Check code style` and pass the `SonarCloud Code Analysis` at first.

Maybe it's a problem with validation rules?

image

**Comment by chengshiwen** [comment]
@hailin0 If you are sure that `fall through` is required, you should add the specified comment, for examples:
```
 switch (i) {
   case 1:
     i++; // fall through
   case 2: // OK
     i++;
     // fallthru
}
```

**Comment by lgcareer** [comment]
@hailin0 
I saw what you modified is ok,you need to fix code style.

**Comment by hailin0** [comment]
> @hailin0
> I saw what you modified is ok,you need to fix code style.

please check.

**Review by lgcareer — APPROVED** [review]
+1

**Review by dailidong — APPROVED** [review]
+1
good job

**Pull request merged**
