### PR TITLE
[Bug-3722][ui]fix cannot change password on dev branch. 

### PR DESCRIPTION
**Pull request by xloya**
#3722
fix cannot change password on dev branch.

### CODE REVIEW

**Review by yangyichao-mango — APPROVED** [review]
+1

**Review by dailidong — APPROVED** [review]
+1
good job

**Comment by dailidong** [comment]
thanks for your first contribution, looking forward to your deep participation, please add my wechat(5105710367) or mail(lidongdai@apache.org), when added, please tell me your github id, thx

**Comment by xloya** [comment]
#3760 fix the letter mistake

**Pull request merged**
