### PR TITLE
[Feature-3416][Queue] You can select any yarn queue new feature

### PR DESCRIPTION
**Pull request by BoYiZhang**
When creating Mr / spark / Flink / Waterdrop , it is specified according to the business

issue: #3416 

such as :

image

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Hi,
Please describe the range of queues that will be displayed on the UI. Will it show all the queues in this feature?

**Comment by BoYiZhang** [comment]
> Hi,
> Please describe the range of queues that will be displayed on the UI. Will it show all the queues in this feature?



> Hi,
> Please describe the range of queues that will be displayed on the UI. Will it show all the queues in this feature?

issue: #3416

**Comment by break60** [comment]
Is there any queue deletion restriction on this block, such as tasks that have been associated with the queue, is it impossible for users to delete the queue?

**Comment by BoYiZhang** [comment]
> Is there any queue deletion restriction on this block, such as tasks that have been associated with the queue, is it impossible for users to delete the queue?

This PR deals with [Mr / spark / Flink / waterdrop]

When creating the workflow, you can select the yarn queue

And the content in the yarn queue comes from [yarn queue management]

image


image

image


image



--------------------------------------------------------------------------------------

I took a look at the [yarn queue management] and did not delete the function

If necessary, it can be implemented with a new pr


image

**Review by break60 — APPROVED** [review]
front end +1

**Comment by gaojun2048** [comment]
Thank you for your pr.

Now, yarn queue can only be associate to tenant（租户），the tenant is a hadoop user in a hadoop cluster . 
The yarn queue must be real and the hadoop user must have permission to submit jobs to the yarn queue.
Therefore, I think, if possible, the yarn queue that can be selected when creating the mr task must be the yarn queue associated with the tenant corresponding to the user.

In addition, the current tenant and yarn queue have a one-to-one relationship. So, it is meaningless to let users choose yarn queue. If a tenant can associate multiple yarn queues, it is a good idea to let users choose yarn queue when creating mr tasks.

**Pull request closed without merging**
