### PR TITLE
[Improvement-3612][ui] Workflow version control ui optimize

### PR DESCRIPTION
**Pull request by yangyichao-mango**
## What is the purpose of the pull request

*Workflow version control ui optimize (#3612 )*

## Brief change log

  - *version.vue fix the `1` `2` `3` `4` `5` in issue #3612 *

### CODE REVIEW

**Comment by break60** [comment]
Why not delete the entire column

**Comment by yangyichao-mango** [comment]
> Why not delete the entire column
> image

1. I do not remove this span is for the beauty of ui and I'am not familiar with css. Any suggestion about this?
Before remove span:
image
After remove span:
image

2. And I try to use tooltips, but it still have some problem, your can refer to #3612 conversation about list page description, please help to give some suggestions, Thx a lot~

**Comment by xingchun-chen** [comment]
@yangyichao-mango 
image

**Comment by yangyichao-mango** [comment]
> @yangyichao-mango
> image

Got.

**Comment by yangyichao-mango** [comment]
@chenxingchun done. Please help to review.

**Comment by break60** [comment]
"span"Can be deleted

**Comment by yangyichao-mango** [comment]
> "span"Can be deleted

But if `span` is deleted, it will make the ui of version list ugly, so I just put it for place holder and it will make the list more pretty. I think we can keep it now, if there is need to replace `span` with `css` later, it will be better.

**Comment by break60** [comment]
> > "span"Can be deleted
> 
> But if `span` is deleted, it will make the ui of version list ugly, so I just put it for place holder and it will make the list more pretty. I think we can keep it now, if there is need to replace `span` with `css` later, it will be better.

Delete span, change the first th to <th scope="col" style="min-width: 40px;text-align: left">Version</th>

**Comment by yangyichao-mango** [comment]
@break60 done. Please help to review.

**Comment by qiaozhanwei** [comment]
@break60

**Review by break60 — APPROVED** [review]
+1

**Review by qiaozhanwei — APPROVED** [review]
+1

**Pull request merged**
