### PR TITLE
[Fix-3236][DagHelper]getFlowNodeListPost/getFlowNodeListPre time complexity O(N^N)

### PR DESCRIPTION
**Pull request by wangyanphp**
Change-Id: I1afa6b84e5ff281d3cf406b28e55e78c2cf7549d

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

[DagHelper]getFlowNodeListPost/getFlowNodeListPre time complexity is O(N^N); Thiss might solve the problem

## Brief change log

- Add vistied marked list to function getFlowNodeListPost/getFlowNodeListPre

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Hi,
Please change the title according to the specifications of [1]. Thx a lot~

[1] https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

**Comment by wangyanphp** [comment]
> Hi,
> Please change the title according to the specifications of [1]. Thx a lot~
> 
> [1] https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

done

**Comment by wangyanphp** [comment]
> Hi, can you add JMH test for this change?

sorry, i'm not java developer and writing JMH test has exceeded my abilities. but this code works  in my informal test

**Comment by dailidong** [comment]
good job， could you re-submit this PR to dev branch ? dev-131 will be deleted

**Comment by dailidong** [comment]
thanks for your first contribution, if you need any help, please send mail to dev@dolphinscheduler.apache.org or contact my wechat(510570367),when added, please tell me your github id

**Comment by wangyanphp** [comment]
> good job， could you re-submit this PR to dev branch ? dev-131 will be deleted

ok, i will do it

**Comment by yangyichao-mango** [comment]
> > good job， could you re-submit this PR to dev branch ? dev-131 will be deleted
> 
> ok, i will do it

Hi,
Please make sure which pr is the improvement pr.
image

**Comment by wangyanphp** [comment]
> > > good job， could you re-submit this PR to dev branch ? dev-131 will be deleted
> > 
> > 
> > ok, i will do it
> 
> Hi,
> Please make sure which pr is the improvement pr.
> image

this one.
i will close the other

**Pull request closed without merging**
