### PR TITLE
adds waterdrop plugin

### PR DESCRIPTION
**Pull request by xsbai**
#3035  What is the purpose of the pull request

This pull request adds waterdrop plugin. which links to issue #3080 

## Brief change log

  - *Add waterdrop-plugin to formModel\tasks*
  - *Add waterdrop-node to formModel.vue*
  - *Add waterdrop-icon to dag.scss and config.js*
  - *cite shell tasks for running waterdrop task in TaskManager.java*

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Good job,
Can you link this PR to the corresponding issue ? Thx a lot.

**Comment by xsbai** [comment]
> #3035 What is the purpose of the pull request
> 
> This pull request adds waterdrop plugin.
> 
> ## Brief change log
> * _Add waterdrop-plugin to formModel\tasks_
> * _Add waterdrop-node to formModel.vue_
> * _Add waterdrop-icon to dag.scss and config.js_
> * _cite shell tasks for running waterdrop task in TaskManager.java_
> 
> ## Verify this pull request
> This pull request is code cleanup without any test coverage.



> Good job,
> Can you link this PR to the corresponding issue ? Thx a lot.

the pr is links to issue #3080

**Comment by samz406** [comment]
I think it is possible to write a user manual to facilitate subsequent use by other users

**Comment by dailidong** [comment]
> I think it is possible to write a user manual to facilitate subsequent use by other users

+1, I also think a `how to use waterdrop plugin` document will be better for user, could you do it ?

**Comment by xsbai** [comment]
##### 7.13 waterdrop节点

* 拖动工具栏中的image-20200706102342182任务节点到画板中，如下图所示

image-20200706102519765

* 部署方式：支持client、cluster和local模式

* 队列：指分配到spark中的队列，默认为default

* Master：指进行waterdrop任务的节点，可选yarn或者mesos，当部署方式为local时，默认为本机

* 资源：指waterdrop任务的配置文件，当选择多个文件时，将顺序进行waterdrop任务

* 自定义参数：waterdrop配置文件中的用户自定义参数，会替换脚本中以${变量}的内容

  

> waterdrop配置文件编写，详情请看[waterdrop_config](https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v1/configuration/base)



##### 7.13 waterdrop

* Drag the image-20200706102342182 task node in the toolbar onto the palette and double-click the task node as follows:

image-20200706103807253

* Deploy Mode ：support client、cluster and local
* Queue ：Refers to the queue assigned to spark. Default is the default
* Master ：It refers to the node that performs the waterdrop task. You can select either yarn or mesos. When the deployment mode is local, it is local by default
* Resources：Refers to the configuration file of the waterdrop task. When multiple files are selected, the waterdrop task will be performed in sequence
* Custom parameters: User-defined parameters in waterdrop config file that replace the contents in scripts with ${variables}

> Write waterdrop configuration file. For details, please see [waterdrop_config](https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v1/configuration/base)

**Comment by xsbai** [comment]
> > I think it is possible to write a user manual to facilitate subsequent use by other users
> 
> +1, I also think a `how to use waterdrop plugin` document will be better for user, could you do it ?

I has finished the plugin document in comment，but the project incubator-dolphinscheduler-website is too large to pull down，May you help me to submit a PR to the project? thx a lot. 
btw, the conflicts of en_US.js, which I has resolved, but it's not work.

**Comment by dailidong** [comment]
> > > I think it is possible to write a user manual to facilitate subsequent use by other users
> > 
> > 
> > +1, I also think a `how to use waterdrop plugin` document will be better for user, could you do it ?
> 
> I has finished the plugin document in comment，but the project incubator-dolphinscheduler-website is too large to pull down，May you help me to submit a PR to the project? thx a lot.
> btw, the conflicts of en_US.js, which I has resolved, but it's not work.

good job, I solved the conflict file.
I saw the document but I not found waterdrop related jar? are there some related jars need to be put into the lib directory
and which version for waterdrop is supported now?

**Comment by xsbai** [comment]
> > > > I think it is possible to write a user manual to facilitate subsequent use by other users
> > > 
> > > 
> > > +1, I also think a `how to use waterdrop plugin` document will be better for user, could you do it ?
> > 
> > 
> > I has finished the plugin document in comment，but the project incubator-dolphinscheduler-website is too large to pull down，May you help me to submit a PR to the project? thx a lot.
> > btw, the conflicts of en_US.js, which I has resolved, but it's not work.
> 
> good job, I solved the conflict file.
> I saw the document but I cant found waterdrop related jar? are there some related jars need to be put into the lib directory
> and which version for waterdrop is supported now?

First，the waterdrop usage is like spark or flink, it's through a  shell script to submit task, so you need to set the WATERDROP_HOME in env.sh, and there is no necessary to set the waterdrop jar in lib
Second，the 1.x version of waterdrop is supported, and the 2.x version support is in process of development.

**Comment by break60** [comment]
Please resolve conflicting files

**Comment by break60** [comment]
Your two files are missing commas

**Comment by yangyichao-mango** [comment]
Hi,
I have test this feature in my local env, the jar should be the required field, please add the checker in front-end. And you can refer to Flink component that implement jar existing checker.
image

**Comment by yangyichao-mango** [comment]
Hi,
When I add the plugin and `confirm add`, it will show the error. Please resolve it.
image

**Comment by xsbai** [comment]
> Hi,
> I have test this feature in my local env, the jar should be the required field, please add the checker in front-end. And you can refer to Flink component that implement jar existing checker.
> image

thx！the resources field is need the waterdrop configuration file but not the waterdrop‘s jar，the more details you can get in [waterdrop_conf](https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v1/configuration/base). And it really need a existing checker in front_page, I'll fix it .thx a lot!

**Comment by xsbai** [comment]
> Hi,
> When I add the plugin and `confirm add`, it will show the error. Please resolve it.
> image

I can’t repeat this error. but I think it 's due to the correct configuration file is not selected in the resource field, the file name cannot be read for iteration. I will prompt you to select the correct resource in the front page. Thank you

**Comment by yangyichao-mango** [comment]
> > Hi,
> > When I add the plugin and `confirm add`, it will show the error. Please resolve it.
> > image
> 
> I can’t repeat this error. but I think it 's due to the correct configuration file is not selected in the resource field, the file name cannot be read for iteration. I will prompt you to select the correct resource in the front page. Thank you

Got it~

**Comment by yangyichao-mango** [comment]
Hi,
When I add waterdrop node with `local` mode and confirm save(it will change to `client` mode when the closing moment)[1], and when I double click the waterdrop node again, it still show the client mode[2], but it show nothing error in browser console.

Please locate the bug and resolve it.

[1] 
image

[2] 
image

**Comment by xsbai** [comment]
> Hi,
> When I add waterdrop node with `local` mode and confirm save(it will change to `client` mode when the closing moment)[1], and when I double click the waterdrop node again, it still show the `client` mode[2], but it show nothing error in browser console.
> 
> Please locate the bug and resolve it.
> 
> [1]
> image
> 
> [2]
> image

the first problem it's due to vue's _verification function, and It doesn't affect the final script submission, and I've fixed it
the second problem which is due to the first problem I've fixed it

**Comment by yangyichao-mango** [comment]
Hi,
I think it will be better to add the description about `WATERDROP_HOME` config in document because this `rawscript` is black box for users. could you do it?
image

**Comment by dailidong** [comment]
@yangyichao-mango hi, you did good job too,  very serious and detail work, haha

**Comment by zxbing** [comment]
Will 1.4.0 be published before the Chinese new year ?

**Pull request merged**
