### PR TITLE
[Feature]add presto datasource support

### PR DESCRIPTION
**Pull request by rockxsj**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

update .gitigonre to igonre some files
add presto datasource support

## Brief change log
``` log
        new file:   dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/PrestoDataSource.java
        modified:   .gitignore
        modified:   dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
        modified:   dolphinscheduler-common/pom.xml
        modified:   dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
        modified:   dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/DbType.java
        modified:   dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/BaseDataSource.java
        modified:   dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/DataSourceFactory.java
        modified:   dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
        modified:   dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
        modified:   dolphinscheduler-ui/src/js/conf/home/store/datasource/actions.js
        modified:   pom.xml
```

## Verify this pull request

This pull request is already covered by existing tests.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Good job, adding a new jar requires sending an email to dev and getting approval from PPMC. At the same time, you can refer to the following article to check by yourself first.
https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/development/DS-License.md

**Comment by rockxsj** [comment]
> Good job, adding a new jar requires sending an email to dev and getting approval from PPMC. At the same time, you can refer to the following article to check by yourself first.
> https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/development/DS-License.md

done

**Comment by yangyichao-mango** [comment]
Good job,
Please add test case to resolve the sonar 0.0% coverage.

**Comment by dengc367** [comment]
you need change the presto driver name **com.facebook.presto.jdbc.PrestoDriver** in presto driver configuration, not _io.prestosql.jdbc.PrestoDriver_  when you use the facebook presto-jdbc jar , @rockxsj

**Comment by dengc367** [comment]
I have modify some code from this presto feature and submit another pull request [[Feature]modify some cases from rockxsj:Feature-presto to add presto datasource support](https://github.com/apache/incubator-dolphinscheduler/pull/3468)
thanks @rockxsj for the codes.

**Pull request merged**
