### PR TITLE
[Improvement-4137] remove priorityQueue.size=0 sleep 1 second

### PR DESCRIPTION
**Pull request by GitFireMan**
To improve the performance, remove some unuseful lines. #4137

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@lgcareer hi, sleep 1 min,Is there another reason here?

**Comment by lgcareer** [comment]
> @lgcareer hi, sleep 1 min,Is there another reason here?

If removed `sleep`,it will be blocked when here is no task in queue.If here is some failed dispatch tasks,it need add them to the queue back.

**Review by lgcareer — COMMENTED** [review]
@GitFireMan If remove sleep,it will be blocked when here is no task in queue.If here is some failed dispatch tasks,it need add them to the queue back.
So it's neccesary to keep the code section that you want to remove.

**Comment by GitFireMan** [comment]
@lgcareer I get your mean. To avoid an always failed high-priority task block master consumer. 
Maybe we can use `public E poll(long timeout, TimeUnit unit)` .
code like this
image
image

what do you think about?

**Comment by CalvinKirs** [comment]
> @lgcareer I get your mean. To avoid an always failed high-priority task block master consumer.
> Maybe we can use `public E poll(long timeout, TimeUnit unit)` .
> code like this
> `String taskPriorityInfo = taskPriorityQueue.poll(Constants.SLEEP_TIME_MILLIS, TimeUnit.MILLISECONDS); if(Objects.isNull(taskPriorityInfo)){ continue; }`
> 
> And `TaskPriorityQueueImpl` add a method like this:
> `@Override public String poll(long timeout, TimeUnit unit) throws Exception { return queue.poll(timeout,unit); }`
> 
> what do you think about?

Why do you need to do this? Generally speaking, this is a good solution, but it may not be appropriate here. It does not belong to the PriorityQueue method. To be precise, it does not belong to the PriorityQueue category.

**Comment by GitFireMan** [comment]
@CalvinKirs When a new task put into the `queue`, sleep one second will make the comsumer waiting util one second pass.
But use `poll(timeout,Unit)` can solve this question, and can have some performance promote when the Tasks comes low frequency.
Also it can resolve than an always failed high-priority task block master consumer.

Queue implement used here is `PriorityBlockingQueue` , and poll(timeout,Unit) belongs to `PriorityBlockingQueue` .

**Comment by CalvinKirs** [comment]
> @CalvinKirs When a new task put into the `queue`, sleep one second will make the comsumer waiting util one second pass.
> But use `poll(timeout,Unit)` can solve this question, and can have some performance promote when the Tasks comes low frequency.
> Also it can resolve that an always failed high-priority task block master consumer.
> 
> Queue implement used here is `PriorityBlockingQueue` , and poll(timeout,Unit) belongs to `PriorityBlockingQueue` .

Sorry, I think you can do this.

**Comment by GitFireMan** [comment]
> > @CalvinKirs When a new task put into the `queue`, sleep one second will make the comsumer waiting util one second pass.
> > But use `poll(timeout,Unit)` can solve this question, and can have some performance promote when the Tasks comes low frequency.
> > Also it can resolve that an always failed high-priority task block master consumer.
> > Queue implement used here is `PriorityBlockingQueue` , and poll(timeout,Unit) belongs to `PriorityBlockingQueue` .
> 
> Sorry, I think you can do this.

**Comment by GitFireMan** [comment]
> > @CalvinKirs When a new task put into the `queue`, sleep one second will make the comsumer waiting util one second pass.
> > But use `poll(timeout,Unit)` can solve this question, and can have some performance promote when the Tasks comes low frequency.
> > Also it can resolve that an always failed high-priority task block master consumer.
> > Queue implement used here is `PriorityBlockingQueue` , and poll(timeout,Unit) belongs to `PriorityBlockingQueue` .
> 
> Sorry, I think you can do this.

Can not do this ?

**Comment by CalvinKirs** [comment]
> > > @CalvinKirs When a new task put into the `queue`, sleep one second will make the comsumer waiting util one second pass.
> > > But use `poll(timeout,Unit)` can solve this question, and can have some performance promote when the Tasks comes low frequency.
> > > Also it can resolve that an always failed high-priority task block master consumer.
> > > Queue implement used here is `PriorityBlockingQueue` , and poll(timeout,Unit) belongs to `PriorityBlockingQueue` .
> > 
> > 
> > Sorry, I think you can do this.
> 
> Can not do this ?

You can do as you said, sounds good to me, btw, code style chack fail, you can refer to this article to complete the modification https://dolphinscheduler.apache.org/zh-cn/docs/development/pull -request.html

**Comment by GitFireMan** [comment]
> > > > @CalvinKirs When a new task put into the `queue`, sleep one second will make the comsumer waiting util one second pass.
> > > > But use `poll(timeout,Unit)` can solve this question, and can have some performance promote when the Tasks comes low frequency.
> > > > Also it can resolve that an always failed high-priority task block master consumer.
> > > > Queue implement used here is `PriorityBlockingQueue` , and poll(timeout,Unit) belongs to `PriorityBlockingQueue` .
> > > 
> > > 
> > > Sorry, I think you can do this.
> > 
> > 
> > Can not do this ?
> 
> You can do as you said, sounds good to me, btw, code style check fail, you can refer to this article to complete the modification https://dolphinscheduler.apache.org/zh-cn/docs/development/pull -request.html

Quite appreciate to your suggestion. I will submit a new pr according to the code standard.

**Comment by dailidong** [comment]
@GitFireMan , good first contribution,  your implemention is better,  I like this.  
by the way, this PR need to do update following the doc : https://dolphinscheduler.apache.org/zh-cn/docs/development/pull -request.html,  because the code-style not unify, and please solve confilct files locally

image

if you need any help , please contact me(lidongdai@apache.org or wechat:510570367) , when added, please tell me your github id

you have done good job, let's make it better

**Comment by dailidong** [comment]
I will close this PR , please re-submit a new PR
thanks for your first contribution

**Pull request closed without merging**
