### PR TITLE
Optimizing code

### PR DESCRIPTION
**Pull request by elitecodegroovy**
## What changes did I do?
- Updated the file 'CONTRIBUTING.md' and make the contributing tutorial look good.
- Formatted the file 'ParameterUtils.java' and make the code indent .
- Removed the replicated code in the file 'AlertDao.java'

### CODE REVIEW

**Comment by dailidong** [comment]
good job,  good beginning

I find conflicting files, please solve conflict locally
image

**Comment by elitecodegroovy** [comment]
> good job, good beginning
> 
> I find conflicting files, please solve conflict locally
> image

It has been done.

**Comment by dailidong** [comment]
Please let me know where parameterutils.java is optimized，I can't find 

by the way,  please one pr just for one thing, I will delete parameterutils.java then merge,  and you can submit a new PR if   parameterutils is optimized

**Comment by elitecodegroovy** [comment]
OK！I just indent the code for the file ParamerUtil.java



---Original---

**Comment by dailidong** [comment]
I'm so sorry ，I delete the ParameterUtils.java use the wrong way， it will make the ParameterUtils.java been deleted  on the source code

please submit a new PR (not include ParameterUtils.java), now I close this PR 

sorry again

**Comment by dailidong** [comment]
and you can add my wechat(510570367) or mail: dailidong66@gmail.com, we have developer group, I can invite you if you like

**Pull request closed without merging**
