### PR TITLE
Support SSH Task

### PR DESCRIPTION
**Pull request by peilongwu**
## Support SSH Task

  - The datasource config page support remote server config and test.
  - The DAG's shell task support remote and choose remote server source.
  - The Work Server support SSH's task execute.

### CODE REVIEW

**Comment by break60** [comment]
Unit test coverage is not enough, need to add more ut

**Comment by break60** [comment]
Do not change the front-end .env file

**Comment by dailidong** [comment]
I'm sorry for not review in time. 

I see there are some Conflicting files, please solve it locally,  By theway, don't use fastjson , please replace it with Jackson in your code. we will remove fastjson next version

**Comment by dailidong** [comment]
if you need help, please contact dev@dolphinscheduler.apache.org , or you can add wechat(510570367), when added, please tell me your github id. of course my mail(lidongdai@apache.org )also welcome

**Comment by break60** [comment]
Do not change the front-end .env file

**Comment by break60** [comment]
Do not change the front-end .env file

**Comment by qiaozhanwei** [comment]
please resolve conflicts，Thx

**Comment by peilongwu** [comment]
OK，Got it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 下午5:19
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"裴龙武"<peilongwu@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] Support SSH Task (#2880)





 
please resolve conflicts，Thx

**Comment by gabrywu** [comment]
I think we should not use passphrase to connect remote server, key file is better like : ssh -i /root/.ssh/ido_sch_pro ido@192.168.1.111 -p 7744

**Pull request closed without merging**
