### PR TITLE
[BugFix] isssue #3299

### PR DESCRIPTION
**Pull request by JinyLeeChina**
Fixed alert cannot be notified，when master or worker shutdown。
I think the reason for this is that Jackson can't parse JSON fields with single quotes.

### CODE REVIEW

**Comment by JinyLeeChina** [comment]
> Fixed alert cannot be notified，when master or worker shutdown。
> I think the reason for this is that Jackson can't parse JSON fields with single quotes.

**Comment by qiaozhanwei** [comment]
why all red compile not pass

**Comment by JinyLeeChina** [comment]
Yes, I‘ve fixed

**Comment by yangyichao-mango** [comment]
Hi,
The type of `{'a': "b"}` and `{'a': 'b'}` is not a standard json string, but if we add the `ALLOW_SINGLE_QUOTES`, it will be formatted by `JSONUtils`.
I think a better way to fix this bug is format the original json not to change the JSONUtils.
image

**Comment by JinyLeeChina** [comment]
I think we should be compatible with JSON with single quotation marks

**Comment by JinyLeeChina** [comment]
Update actions.js fixed #3351

**Comment by lenboo** [comment]
Hi,

Please change the title to [Fix-3299][ui] process_definition_json contains definitionList，but this definitionList is not use . Thx

**Comment by break60** [comment]
+1

**Comment by lenboo** [comment]
there is another pr refer to the issue, so i will close this.

**Pull request closed without merging**
