### PR TITLE
[Improvement][alert] Refactor alert module to fix code smell

### PR DESCRIPTION
**Pull request by Segun-Ogundipe**
## What is the purpose of the pull request

This pull request fixes some of the code smell and vulnerability reported by sonar
Fixes part of #3325 

## Brief change log

  - *Refactor files to fix code smell and vulnerability reported by sonar in the alert module*

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by Segun-Ogundipe** [comment]
Hi @dailidong, @CalvinKirs, I have started fixing code smells and vulnerability with the alert module. I will move to other modules once this PR is accepted. Please review.

**Comment by CalvinKirs** [comment]
> Hi @dailidong, @CalvinKirs, I have started fixing code smells and vulnerability with the alert module. I will move to other modules once this PR is accepted. Please review.

Cool, but there are still 10 code smells, can you solve it?

**Comment by dailidong** [comment]
good job，please fix CODE_SMELL problem ,  check the detail info:  https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=4434&resolved=false&types=CODE_SMELL

if you meet any problem ,please contact me (lidongdai@apache.org)

**Comment by Segun-Ogundipe** [comment]
Hi @dailidong, @CalvinKirs, the 10 code smell being reported by sonar are actually not code smells. Sonar is registering them as code smells because the value is being taken from a variable and sonar thinks the value is not a regular expression but it actually is. The tests for the EnterpriseWechatUtils file will fail if I follow sonar suggestions and replace the call to `replaceAll()` with `replace()`

**Review by dailidong — APPROVED** [review]

**Comment by dailidong** [comment]
> Hi @dailidong, @CalvinKirs, the 10 code smell being reported by sonar are actually not code smells. Sonar is registering them as code smells because the value is being taken from a variable and sonar thinks the value is not a regular expression but it actually is. The tests for the EnterpriseWechatUtils file will fail if I follow sonar suggestions and replace the call to `replaceAll()` with `replace()`

+1
yes,  you  are right,  good job

**Pull request merged**
