### PR TITLE
[Fix][UI]: fix re-login problem in new tab and state synchronization problem in multiple tabs

### PR DESCRIPTION
**Pull request by chengshiwen**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

- **fix re-login problem in new tab**
- **fix state synchronization problem in multiple tabs**

## Brief change log

- 1e5da637 fix(ui): re-login problem in new tab
- afeec6ca refresh page in new tab automatically
- 72e63d26 support to reload router view in lightweight

The new re-login condition is `(!sIdCookie || (sessionId && sessionId !== sIdCookie)) && requstUrl !== 'login'`

assume `requstUrl !== 'login'`:

- `sIdCookie` is `undefined` or `null`: require re-login
- `sessionId && sessionId !== sIdCookie`: require re-login when sessionId changed
  - attention that `sessionId` may be `null` but `sIdCookie` is non-empty

And, the state synchronization problem in multiple tabs has fixed in this pr.

## Verify this pull request

*(Please pick either of the following options)*

This change added tests and can be verified as follows:

**Before fix**:
- **re-login**
image
- **state synchronization**:
image

**After fix**:
- **re-login**:
image
- **state synchronization**:
image

### CODE REVIEW

**Comment by break60** [comment]
In the past, the same browser can open multiple tabs, but there will be a problem. For example, the task of a certain tab is changed, and the task of another tab will not be updated synchronously. Is there a better way to support multiple tabs? And if a certain tab is changed, other tabs can be updated simultaneously

**Comment by chengshiwen** [comment]
@break60 Thanks for reply.

The action to require re-login in new tab for logged-in user is not a good user interaction experience, so I submit this pr to solve the problem.

For the state synchronization in multiple tabs, this problem appears in most front-end projects. In essence, each tab is independent of each other, and http request is also stateless. To solve this problem, listening event of `localStorage` may be possible. Specifically,
- Chage `localStorage` when some state changed in a certain tab
- Add event listener for key `storage` in another tab
  - This means that you can trigger a page refresh, or whatever you want to do

The sample code is as follow:
image

The example effect is as follow:
image

**Comment by break60** [comment]
> The action to require re-login in new tab for logged-in user is not a good user interaction experience, so I submit this pr to solve the problem.
> 
> For the state synchronization in multiple tabs, this problem appears in most front-end projects. In essence, each tab is independent of each other, and http request is also stateless. To solve this problem, listening event of `localStorage` may be possible. Specifically,
> 
> * Chage `localStorage` when some state changed in a certain tab
> * Add event listener for key `storage` in another tab
>   
>   * This means that you can trigger a page refresh, or whatever you want to do
> 
> The sample code is as follow:

Very good, can it be added to the current pr

**Comment by chengshiwen** [comment]
I will add it tomorrow

**Review by break60 — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
+1

**Comment by geosmart** [comment]
this pr make a new problem!!!
when you edit dag node , update a sql and click ok(not save the dag)
switch tab to copy a sql, and switch back,
the sql change is lost !

**Comment by CalvinKirs** [comment]
> this pr make a new problem!!!
> when you edit dag node ,
> eg:
> 
> 1. update a sql and click ok(not save the dag)
> 2. switch tab to copy something
> 3. switch to ds dag edit tab
>    now open the node param ,found that the sql change is lost !

Can you create a new issue?

**Comment by chengshiwen** [comment]
@geosmart @break60 
This is a problem caused by state synchronization in new tab. For state synchronization, we will refresh page in new opened page.
If we don't do this, the issue **the task of a certain tab is changed, and the task of another tab will not be updated synchronously** referenced by @break60 will occur.

**Comment by geosmart** [comment]
> @geosmart @break60
> This is a problem caused by state synchronization in new tab. For state synchronization, we will refresh page in new opened page.
> If we don't do this, the issue **the task of a certain tab is changed, and the task of another tab will not be updated synchronously** referenced by @break60 will occur.

I know the visibilitychange can fix the sync problem
but the scenario of dag editor can not refresh to make the data loss
the dag design is usauly need to switch tab

**Comment by chengshiwen** [comment]
This merged pr is based on `visibilitychange `

**Pull request merged**
