### PR TITLE
[Feature-#3083]Select and drag dag

### PR DESCRIPTION
**Pull request by satcblue**
## What is the purpose of the pull request

- Convenient for users to drag and drop, when user use the dag, he should drag one by one. Now, he can select one or more to drag by pressing the key of 'ctrl' or 'meta'.
## Brief change log
  - Add multiDrag.js

### CODE REVIEW

**Comment by break60** [comment]
Please don't change the code style of dag.vue page, otherwise I don't know what you changed

**Comment by yangyichao-mango** [comment]
Good job,
We should commit an issue before we do this work. Can you commit a new feature issue about your work and link this PR to that issue?

**Comment by satcblue** [comment]
> Please don't change the code style of dag.vue page, otherwise I don't know what you changed

sorry about that, i will redo dag.vue page.

**Comment by satcblue** [comment]
> Good job,
> We should commit an issue before we do this work. Can you commit a new feature issue about your work and link this PR to that issue?

thx, get it. it's my first time to create PR. I will recheck my code these days, then commit a new feature issue.

**Comment by satcblue** [comment]
> > Good job,
> > We should commit an issue before we do this work. Can you commit a new feature issue about your work and link this PR to that issue?
> 
> thx, get it. it's my first time to create PR. I will recheck my code these days, then commit a new feature issue.

done

**Comment by break60** [comment]
> > > Good job,
> > > We should commit an issue before we do this work. Can you commit a new feature issue about your work and link this PR to that issue?
> > 
> > 
> > thx, get it. it's my first time to create PR. I will recheck my code these days, then commit a new feature issue.
> 
> done

I don’t see your associated issue, please give an issue to describe this function, and then connect to this pr

**Comment by satcblue** [comment]
> > > > Good job,
> > > > We should commit an issue before we do this work. Can you commit a new feature issue about your work and link this PR to that issue?
> > > 
> > > 
> > > thx, get it. it's my first time to create PR. I will recheck my code these days, then commit a new feature issue.
> > 
> > 
> > done
> 
> I don’t see your associated issue, please give an issue to describe this function, and then connect to this pr

such like this? #3068

**Comment by break60** [comment]
very good， front end +1

**Comment by lenboo** [comment]
> very good， front end +1

you can Approve +1 at “File Changed”

**Comment by dailidong** [comment]
thanks for your first contribution, if you need help, please contact dev@dolphinscheduler.apache.org or wechat(510570367), when added, please tell your github id

**Pull request merged**
