### PR TITLE
add AbstractServer.java

### PR DESCRIPTION
**Pull request by dailidong**
add AbstractServer.java

### CODE REVIEW

**Comment by djkevincr** [comment]
I am getting following compilation failure on current dev branch.
```
[INFO] 31 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] escheduler ......................................... SUCCESS [  0.376 s]
[INFO] escheduler-common .................................. SUCCESS [  2.331 s]
[INFO] escheduler-dao ..................................... SUCCESS [  2.790 s]
[INFO] escheduler-rpc ..................................... SUCCESS [  2.166 s]
[INFO] escheduler-alert ................................... SUCCESS [  5.419 s]
[INFO] escheduler-server .................................. FAILURE [  0.796 s]
[INFO] escheduler-api ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.422 s
[INFO] Finished at: 2019-09-08T13:14:17+05:30
[INFO] Final Memory: 182M/1081M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project escheduler-server: Compilation failure: Compilation failure:
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[32,34] error: cannot find symbol
[ERROR] package cn.escheduler.server.master
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[55,34] error: cannot find symbol
[ERROR] class AbstractServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[48,34] error: cannot find symbol
[ERROR] class AbstractServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[101,12] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[131,4] error: method does not override or implement a method from a supertype
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[143,20] error: cannot find symbol
[ERROR] variable workerServer of type WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[150,8] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[150,28] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[158,36] error: incompatible types: WorkerServer cannot be converted to IStoppable
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[163,56] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[190,22] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[193,97] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[199,4] error: method does not override or implement a method from a supertype
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[257,26] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[257,25] error: illegal start of type
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[258,16] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/worker/WorkerServer.java:[259,16] error: cannot find symbol
[ERROR] class WorkerServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[77,12] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[100,4] error: method does not override or implement a method from a supertype
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[109,20] error: cannot find symbol
[ERROR] variable masterServer of type MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[116,8] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[116,28] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[120,34] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[129,36] error: incompatible types: MasterServer cannot be converted to IStoppable
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[134,56] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[139,27] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[182,4] error: method does not override or implement a method from a supertype
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[243,26] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[243,25] error: illegal start of type
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[244,16] error: cannot find symbol
[ERROR] class MasterServer
[ERROR] /home/djkevincr/apache_member/incubator-dolphinscheduler/escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java:[245,16] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :escheduler-server

```

**Comment by djkevincr** [comment]
Locally tested this PR and resolves above mentioned compilation error.
@dailidong Shall we merge this PR?

**Comment by dailidong** [comment]
first，thanks for paying attention to our DolphinScheduler project！
Yes, , this AbstractServer class is needed. Because it has just been transferred to the apache organization, there is no related permission to merge this class. You can first merge this pr locally.


At the same time, it needs to be explained that in order to add some big features and make the licenses meet the requirements of apache A and B, the dev branch is undergoing major changes.
the dev branch changes will be faster！

**Comment by dailidong** [comment]
if needed，this is the document of dolphinschedule：
https://analysys.github.io/easyscheduler_docs  （not transfer to apache organization yet ）

**Comment by dailidong** [comment]
and this is R&D plan recently: 

https://github.com/apache/incubator-dolphinscheduler/milestone/6

**Comment by djkevincr** [comment]
@dailidong Thank you for the quick for response. I think ASF accounts for you are being created and you will receive them, once it s done. I will go through material provided, that will be really helpful to get things started. :)

**Pull request merged**
