### PR TITLE
[FIX-#4178][api] Start the workflow, the prompt is incorrect 

### LINKED ISSUE #4178: [Bug][api] Start the workflow, the prompt is incorrect
It should be reminded: check workflow definition errors
image

**Which version of Dolphin Scheduler:**
 -[1.3.3]

### PR DESCRIPTION
**Pull request by zt-1997**
Modify the status class in the dolphinscheduler-api module, Chinese prompt error.
image

this close #4178

### CODE REVIEW

**Comment by zt-1997** [comment]
我这个pr是解决这个issue
https://github.com/apache/incubator-dolphinscheduler/issues/4178

**Review by dailidong — APPROVED** [review]
+1
good job

**Comment by dailidong** [comment]
thanks for your contribution, looking forward to your deep participation

**Comment by wen-hemin** [comment]
---
    @ApiException(CHECK_PROCESS_DEFINITION_ERROR)
    public Result startCheckProcessDefinition(@ApiIgnore @RequestAttribute(value = Constants.SESSION_USER) User loginUser,
                                              @RequestParam(value = "processDefinitionId") int processDefinitionId) {
        logger.info("login user {}, check process definition {}", loginUser.getUserName(), processDefinitionId);
        Map<String, Object> result = execService.startCheckByProcessDefinedId(processDefinitionId);
        return returnDataList(result);
    }
---
When API execute to failed, throw an unhandled exception, return status of CHECK_PROCESS_DEFINITION_ERROR.
So, set to "检查工作流定义失败" more appropriate

**Pull request merged**
