### PR TITLE
[new feature][#711] add flink support 

### PR DESCRIPTION
**Pull request by lihongyu666**
add flink component. 
administrator should make sure that worker servers run in a flink environment before use,
and add flink path to .escheduler_env.sh .

添加flink组件
使用前，管理员需确认worker所在的机器上有flink环境。并在.escheduler_env.sh文件添加flink path

### CODE REVIEW

**Comment by dailidong** [comment]
@qiaozhanwei , please review !

**Comment by LoveEvenWong** [comment]
> @qiaozhanwei , please review !

I have already submitted this function.

#711

**Comment by LoveEvenWong** [comment]
Is there any difference between you and me? I didn't see it.

**Comment by LoveEvenWong** [comment]
> add flink component.
> administrator should make sure that worker servers run in a flink environment before use,
> and add flink path to .escheduler_env.sh .
> 
> 添加flink组件
> 使用前，管理员需确认worker所在的机器上有flink环境。并在.escheduler_env.sh文件添加flink path

Is there any difference between you and me? I didn't see it.

**Comment by Baoqi** [comment]
Thanks for your contribution.  Since we have merged another Flink support PR into dev branch, so, I think we need to close this PR. 

But we still appreciate your contribute, thanks. Look forward to your next contribution.

**Comment by dailidong** [comment]
Look forward to your next contribution！

**Pull request closed without merging**
