### PR TITLE
feat: add plugin management for alert service

### PR DESCRIPTION
**Pull request by hgaol**
## What is the purpose of the pull request

Adding plugin management ability for Alert service. With it, user can only depend the `dolphinscheduler-plugin-api` package, and implement `AlertPlugin` and `AlertPluginProvider`, and provide a resource file with name of the implement class for `AlertPluginProvider`. Which use Java [SPI](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html#limitations-of-the-service-loader-api) feature.

In a nutshell, user can implement different alert methods, and package all classes and dependencies in a single jar file as a plugin way. 

Here already give some utilities class to help developer to implement their own plugin. i.e. `PropertyUtils`, which read the configuration file named `plugin.properties`, and developer can get properties using this class.

Developers do not need to involve log dependencies, just use `slf4j` to create the `Logger`, which included in the `dolphinscheduler-plugin-api` package.

Currently I just keep same with the original email and enterprise wechat, and there are no different plugin for different alert handler logic. It also need collaborate with front-end engineer and may a long way to go. Also, I keep the original email and enterprise wechat just in alert module source code, I think the frequently used plugin should keep in the source code.

I also plan to implement the default webhook plugin. :) 

## Brief change log

  - Added `dolphinscheduler-plugin-api` module for developers to implement their own alert plugin.
  - Added some classes such as `PluginClassLoader`, `PluginManager` and its implementation class `FilePluginManager` in `dolphinscheduler-common` module under the `plugin` package.
  - Updated the `dolphinscheduler-alert` module with the plugin way, and added some tests.

## Verify this pull request

  - *Added some tests in `dolphinscheduler-plugin-api` and `dolphinscheduler-alert` packages*.
  - *Updated some tests in `dolphinscheduler-alert`*.
  - *Tested email function, and didn't test enterprise wechat, cause I don't have the environments. If anyone can do that, it's very appreciate.*

### CODE REVIEW

**Comment by dailidong** [comment]
SonarCloud Quality Gate failed.

**Comment by hgaol** [comment]
#2553 
Also who knows how to solve the `server start failed` error in e2e test?

**Comment by hgaol** [comment]
> Merging #2572 into dev will decrease coverage by 0.32%.
> Please fix it.

Sure, let do it

**Comment by hgaol** [comment]
Sorry, for

**Pull request merged**
