### PR TITLE
[Fix][API] Condition task NullPointerException

### PR DESCRIPTION
**Pull request by hailin0**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

Fix NullPointerException when save condition task.

[ProcessDefinitionServiceImpl.java#L242](https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java#L242)

## Brief change log

changes:
Return empty List\<ResourceInfo\> at org.apache.dolphinscheduler.common.task.conditions.ConditionsParameters#getResourceFilesList

for example:
[SubProcessParameters.java#L47](https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/subprocess/SubProcessParameters.java#L47)

### CODE REVIEW

**Comment by hailin0** [comment]
@dailidong

**Comment by CalvinKirs** [comment]
you have a D-class code smell, which causes the sonar check to fail.please check.

**Review by lgcareer — APPROVED** [review]
+1

**Comment by lgcareer** [comment]
> sonar check to fail.please check.

hi,I saw it's pr only change one line,but the code smell shows it's duplication rate is 50%,So I think it can be merged.

**Comment by CalvinKirs** [comment]
> > sonar check to fail.please check.
> 
> hi,I saw it's pr only change one line,but the code smell shows it's duplication rate is 50%,
> may be it is a problem of the code smell rule,So I think it can be merged.

Yes you are right

**Review by CalvinKirs — APPROVED** [review]
+1

**Pull request merged**
