### PR TITLE
[Improvement-4435][datasource] the datasource tests the connection and returns details when the connection is wrong

### LINKED ISSUE #4435: [Improvement][datasource] the datasource tests the connection and returns details when the connection is wrong
**Describe the question**
the datasource tests the connection and returns details when the connection is wrong

**What are the current deficiencies and the benefits of improvement**
- When the data source is connected incorrectly, the detailed log needs to be queried on the server

**Which version of DolphinScheduler:**
 -[dev]

I will fix it

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request
this PR closes #4435 
the datasource tests the connection and returns details when the connection is wrong

## Brief change log
- BaseDataSource add getConnection

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.*

image

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Cool, but there are still 17 code smells, can you solve it?

**Comment by zhuangchong** [comment]
> Cool, but there are still 17 code smells, can you solve it?

done.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
I temporarily linked it to 1.4.0, we can later determine whether it needs to be released in 1.3.5.

**Pull request merged**
