### PR TITLE
Feature add user state

### PR DESCRIPTION
**Pull request by Rubik-W**
Supplement sql script.

### CODE REVIEW

**Comment by gabrywu** [comment]
@Rubik-W Does this PR still need to be merged?

**Comment by lgcareer** [comment]
@Rubik-W Whether this field `status` add in the sql/upgreade folder

**Comment by qiaozhanwei** [comment]
please solve conflicting

**Comment by Rubik-W** [comment]
> please solve conflicting files locally

fixed

**Pull request merged**
