### PR TITLE
[Improvement-4187][Master] Add log exception stack information

### LINKED ISSUE #4187: [Improvement][Master] Print exception information
Today we found that the log file has more than 100 g

File name: 'dolphin scheduler masterserver- xxxx.out '

After opening the log, it is unable to locate the exception location. Stack information needs to be added to the log

The output log is as follows:

```
[ERROR] 2020-12-09 09:41:50.777  - [taskAppId=TASK-1919-34759-100696]:[156] - wait task quit failed, instance id:34759, task id:100696
[ERROR] 2020-12-09 09:41:50.781  - [taskAppId=TASK-1917-7841-18206]:[154] - exception
java.lang.NullPointerException: null
[ERROR] 2020-12-09 09:41:50.781  - [taskAppId=TASK-1917-7841-18206]:[156] - wait task quit failed, instance id:7841, task id:18206
[ERROR] 2020-12-09 09:41:50.786  - [taskAppId=TASK-1919-34759-100696]:[154] - exception
java.lang.NullPointerException: null
[ERROR] 2020-12-09 09:41:50.786  - [taskAppId=TASK-1919-34759-100696]:[156] - wait task quit failed, instance id:34759, task id:100696
[ERROR] 2020-12-09 09:41:50.788  - [taskAppId=TASK-1919-33805-97659]:[154] - exception
java.lang.NullPointerException: null
[ERROR] 2020-12-09 09:41:50.788  - [taskAppId=TASK-1917-7841-18206]:[154] - exception
java.lang.NullPointerException: null
[ERROR] 2020-12-09 09:41:50.788  - [taskAppId=TASK-1919-33805-97659]:[156] - wait task quit failed, instance id:33805, task id:97659
[ERROR] 2020-12-09 09:41:50.788  - [taskAppId=TASK-1917-7841-18206]:[156] - wait task quit failed, instance id:7841, task id:18206
[ERROR] 2020-12-09 09:41:50.795  - [taskAppId=TASK-1917-7841-18206]:[154] - exception
java.lang.NullPointerException: null
[ERROR] 2020-12-09 09:41:50.795  - [taskAppId=TASK-1917-7841-18206]:[156] - wait task quit failed, instance id:7841, task id:18206
[ERROR] 2020-12-09 09:41:50.798  - [taskAppId=TASK-1919-34759-100696]:[154] - exception
java.lang.NullPointerException: null
```

### PR DESCRIPTION
**Pull request by BoYiZhang**
this close #4187 

Add log exception stack information

```
e.printStackTrace();

```

Only one line of code is added, no test case is needed

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
(org.slf4j.Logger#error(java.lang.String, java.lang.Throwable)) Does this not meet your needs?

**Comment by BoYiZhang** [comment]
> (org.slf4j.Logger#error(java.lang.String, java.lang.Throwable)) Does this not meet your needs?

The location of the error code cannot be located because there is no stack information for the output exception

You can see the issue #4187


Or are there other reasons for not outputting exception stack information?

**Comment by CalvinKirs** [comment]
> > (org.slf4j.Logger#error(java.lang.String, java.lang.Throwable)) Does this not meet your needs?
> 
> The location of the error code cannot be located because there is no stack information for the output exception
> 
> You can see the issue #4187
> 
> Or are there other reasons for not outputting exception stack information?

you try? Whether logger.eeror() can achieve the effect of e.printStack

**Comment by CalvinKirs** [comment]
maybe should setOmitStackTraceInFastThrow?

**Pull request closed without merging**
