### PR TITLE
refactor-worker merge to dev

### PR DESCRIPTION
**Pull request by qiaozhanwei**
issue #1658
This modify main point :
1，Master kill task use netty communication
2，cpu and memory loabalance selector development
3，Master/Worker heartbeat refactor
4，Worker group refactor
5，ProcessInstance and TaskInstance priority refactor
6，Master/Worker fault tolerant refactor
7，Worker server remove db dependent
8，Configuration file optimization

### CODE REVIEW

**Comment by Technoboy-** [comment]
+1
👍

**Comment by dailidong** [comment]
Unit Test failed？

**Comment by qiaozhanwei** [comment]
refactor-worker branch configuration file modified，dockerfile is old，so unit test failed，dockerfile is need modify

**Comment by liwenhe1993** [comment]
I will do it



发自我的iPhone


------------------ Original ------------------

**Comment by gaojun2048** [comment]
@githubzhangchunyang  some config file is modified , the ambari plugin need update

**Comment by gaojun2048** [comment]
@githubzhangchunyang  some config file is modified , the ambari plugin need update

**Comment by githubzhangchunyang** [comment]
OK










At 2020-04-08 18:03:53, "gaojun2048" <notifications@github.com> wrote:

@githubzhangchunyang some config file is modified , the ambari plugin need update

**Comment by break60** [comment]
frontend +1

**Comment by Technoboy-** [comment]
test and coverage seems to satisfy.
+1

**Comment by xingchun-chen** [comment]
+1

**Comment by Technoboy-** [comment]
+1

**Pull request merged**
