### PR TITLE
增加打开yarn页面的功能

### PR DESCRIPTION
**Pull request by LoveEvenWong**
增加功能: 当任务是flink或spark时,运行完任务，在查看日志功能后面增加了一个“打开yarn页面”的功能，可以直接跳转到yarn页面 目前，如果要查看yarn详情，需要打开yarn页面，个人觉得有必要增加这个功能，请审核是否需要
使用时需要将_openYarnPage()方法中的yarnPageAddress　替换为自己的地址

### CODE REVIEW

**Comment by iamnotgay** [comment]
good

**Comment by dailidong** [comment]
please add my wechat: 510570367,  there are some other things to discuss!

**Comment by iamnotgay** [comment]
Here are some questions.    
image

the method  _judgeType and  _openYarnPage is not in methods:{}

When I was running, it reported a mistake.

i think  is ok   ->
image

**Comment by LoveEvenWong** [comment]
you are right

**Comment by LoveEvenWong** [comment]
> Here are some questions.
> image
> 
> the method _judgeType and _openYarnPage is not in methods:{}
> 
> When I was running, it reported a mistake.
> 
> i think is ok ->
> image

yes you are right i，sorry I don't have the correct copy code　from my project to my repository

**Pull request closed without merging**
