### PR TITLE
[Improvement][*] Refactor code to fix code smell and vulnerability

### LINKED ISSUE #3325: [Improvement][*] Improvement the code reported by sonar
**Describe the improvement**

#3321 is for bug reported by sonar.
This issue is for `code smell` and `VULNERABILITY` part reported by sonar, and is the sub-task of #3321

### PR DESCRIPTION
**Pull request by Segun-Ogundipe**
## What is the purpose of the pull request

This pull request fixes some of the code smell and vulnerability reported by sonar
Fixes #3325 

## Brief change log

  - *Refactor files to fix code smell and vulnerability reported by sonar*

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Hi, has this function been completed? If completed, please let me know, and I will start review.thx

**Comment by Segun-Ogundipe** [comment]
Yeah, still working on it. Will make it ready for review as soon as I'm done which should be very soon

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, @dailidong, @djkevincr, this PR is ready for review

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs, @dailidong, @djkevincr, this PR is ready for review

deeply thanks you  for your contribution, but there are some conflicting files you need to deal with

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, I have resolved the conflict but a test is failing, "testGenExcelFileByCheckDir()" method of the ExelUtilsTest file from the alert project. Is that normal? as I don't think it's failing because of the refactoring I did

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, I have updated the codebase to fix the conflict

**Comment by CalvinKirs** [comment]
hi, very good, but I noticed that Sonar check fail, it shows the presence of 5 Bugs ,
 50 Vulnerabilities(B),
23 Code Smells(A).
Can you fix it first?

**Comment by Segun-Ogundipe** [comment]
Yes, I'll do that

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, the 3 remaining bugs are from the DAG file in the common project. Three fields are declared with the `volatile` keyword and they are what sonarcloud tags as bugs. Can I remove the `volatile` keyword or is there a better way to make it work?

I'm also trying to increase the code coverage to get it over 33% but there are some tests that are ignored are not letting the codes I added to get covered. Please advice about what to do here.

The 53 vulnerabilities are from files I refactored to fix code vulnerabilities previously reported by sonar. It stills complain about them even though I have fixed them. Is there a way for me to fix this?

I'll really appreciate your guidance here. Thanks.

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs, the 3 remaining bugs are from the DAG file in the common project. Three fields are declared with the `volatile` keyword and they are what sonarcloud tags as bugs. Can I remove the `volatile` keyword or is there a better way to make it work?
> 
> I'm also trying to increase the code coverage to get it over 33% but there are some tests that are ignored are not letting the codes I added to get covered. Please advice about what to do here.
> 
> The 53 vulnerabilities are from files I refactored to fix code vulnerabilities previously reported by sonar. It stills complain about them even though I have fixed them. Is there a way for me to fix this?
> 
> I'll really appreciate your guidance here. Thanks.

If it is convenient, it is recommended to split into multiple PRs for submission.

**Comment by Segun-Ogundipe** [comment]
What part should I split into another PR. The test coverage needs to be increased to at least 33% to pass sonar check. Should I leave test coverage out of this PR?

**Comment by dailidong** [comment]
hi, @Segun-Ogundipe , good job,  it will better to split this PR  to multi prs,  don't change so many files in one PR , it's better not to exceed 20 files in one PR , so I will close this PR , please submit new PRs, thx

By the way,  I'm sorry for deleting AlertGroupController.java by mistake when I  review these files.

**Comment by dailidong** [comment]
> What part should I split into another PR. The test coverage needs to be increased to at least 33% to pass sonar check. Should I leave test coverage out of this PR?

you can split it according the module, like dolphinscheduler-alert、dolphinscheduler-api and so on.  just remember don't includes too many files in one PR. because review these files will be difficult

**Comment by Segun-Ogundipe** [comment]
> > What part should I split into another PR. The test coverage needs to be increased to at least 33% to pass sonar check. Should I leave test coverage out of this PR?
> 
> you can split it according the module, like dolphinscheduler-alert、dolphinscheduler-api and so on. just remember don't includes too many files in one PR. because review these files will be difficult
> 
> please contact me ([lidongdai@apache.org](mailto:lidongdai@apache.org)) when meeting any problem

Thanks for the explanation. I'll get right on it

**Pull request closed without merging**
