### PR TITLE
remove duplicated code

### PR DESCRIPTION
**Pull request by zjcnb**
remove duplicated code

### CODE REVIEW

**Comment by zjcnb** [comment]
> how about keeping the code the same ?
> like : add TableField in Alert class

I don't know，@TableField annotation，It is need to retain？ i think it's can remove for this project

**Comment by Technoboy-** [comment]
> > how about keeping the code the same ?
> > like : add TableField in Alert class
> 
> I don't know，@TableField annotation，It is need to retain？ i think it's can remove for this project

why did you keep it in AccessToken?  I think we should keep the same manager .

**Comment by zjcnb** [comment]
> > > how about keeping the code the same ?
> > > like : add TableField in Alert class
> > 
> > 
> > I don't know，@TableField annotation，It is need to retain？ i think it's can remove for this project
> 
> why did you keep it in AccessToken? I think we should keep the same manager .

this project has @TableField annotation  already， I didn't add it

**Comment by Technoboy-** [comment]
> > > > how about keeping the code the same ?
> > > > like : add TableField in Alert class
> > > 
> > > 
> > > I don't know，@TableField annotation，It is need to retain？ i think it's can remove for this project
> > 
> > 
> > why did you keep it in AccessToken? I think we should keep the same manager .
> 
> this project has @TableField annotation already， I didn't add it

I mean : try to add @TableField in Alert class to keep code in the same style.

**Comment by zjcnb** [comment]
> > > > > how about keeping the code the same ?
> > > > > like : add TableField in Alert class
> > > > 
> > > > 
> > > > I don't know，@TableField annotation，It is need to retain？ i think it's can remove for this project
> > > 
> > > 
> > > why did you keep it in AccessToken? I think we should keep the same manager .
> > 
> > 
> > this project has @TableField annotation already， I didn't add it
> 
> I mean : try to add @TableField in Alert class to keep code in the same style.

ok!

**Comment by Technoboy-** [comment]
> > > > > > how about keeping the code the same ?
> > > > > > like : add TableField in Alert class
> > > > > 
> > > > > 
> > > > > I don't know，@TableField annotation，It is need to retain？ i think it's can remove for this project
> > > > 
> > > > 
> > > > why did you keep it in AccessToken? I think we should keep the same manager .
> > > 
> > > 
> > > this project has @TableField annotation already， I didn't add it
> > 
> > 
> > I mean : try to add @TableField in Alert class to keep code in the same style.
> 
> ok!

Hi, bro,  did you need any help ? you can send me a email

**Comment by Technoboy-** [comment]
Hi bro, as we discuss, we want to remove lombok dependancy , so try to remove @Data annotation

**Comment by dailidong** [comment]
@zjcnb ,  hello,  could you submit another pr,  for now, this pr has conflicted with DS,   if you submit a new   
pr, please remember  removing @DaTa ,  We have always wanted to reduce third-party dependence. 

thanks you for your contribution again

**Pull request closed without merging**
