### PR TITLE
dag add close buttion

### PR DESCRIPTION
**Pull request by BoYiZhang**
dag add close buttion

#3190

### CODE REVIEW

**Comment by dailidong** [comment]
@break60 please review , thx

**Comment by break60** [comment]
Re-update

**Comment by BoYiZhang** [comment]
e2e test error .

```
Run actions/upload-artifact@v1
##[error]Path does not exist /var/lib/docker/volumes/docker-swarm_dolphinscheduler-logs/_data
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.267.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Comment by xingchun-chen** [comment]
Since the close button is added to the dag page, the xpath path of the save button changes. You need to change the xpath path of CLICK_SAVE_WORKFLOW_BUTTON of org.apache.dolphinscheduler.locator.project.CreateWorkflowLocator
image

**Comment by qiaozhanwei** [comment]
SonarCloud Code Analysis  is not running . please retry commit. Thx

**Comment by BoYiZhang** [comment]
> SonarCloud Code Analysis is not running . please retry commit. Thx

It has been re submitted twice, but sonarcloud code analysis is not running

**Comment by break60** [comment]
+1

**Pull request merged**
