### PR TITLE
[fix-#3843][api]When update workflow definition,if name already exists, the prompt is not friendly

### PR DESCRIPTION
**Pull request by lgcareer**
## What is the purpose of the pull request

*When update workflow definition,if name already exists, the prompt is not friendly*

## Brief change log

*When update workflow definition,if name already exists, the prompt is not friendly*

### CODE REVIEW

**Review by lenboo — APPROVED** [review]
+1

**Comment by DSExtension** [comment]
please submit another pr to dev branch.

**Comment by zhuangchong** [comment]
#3879

When the workflow definition is updated, it will first check the API-verifyProcessDefinitionName method of the workflow definition name, and execute the workflow definition update method. Is it necessary to check whether the workflow name exists when updating in the ProcessDefinitionService class.

---
当工作流定义更新时，会先处罚工作流定义名称检查API-verifyProcessDefinitionName方法,在执行工作流定义更新方法。是否还有必要在ProcessDefinitionService类中更新时候再去检查工作流名称是否存在.

**Comment by lgcareer** [comment]
@zhuangchong When update the process definition,didn't execute the verifyProcessDefinitionName,Now only execute the update api.

**Comment by zhuangchong** [comment]
@lgcareer 
Are you talking about direct calls via API or via web?

Called via web, each click of the update button in dag.vue will trigger the method in udp.vue to call the backend verifyProcessDefinitionName(projects/${state.projectName}/process/verify-name)
image

In fact, when you click the update button, you can also see that you first request verifyProcessDefinitionName(projects/${state.projectName}/process/verify-name) in the browser console
In request updateProcessDefinition(projects/${state.projectName}/process/update)
image
image

If you call the API directly, you need to consider that there are two methods that have been validated for the workflow definition name. How to design better

---

你说的是API方式直接调用还是通过web方式来调用？

通过web方式调用，在dag.vue里面每次点击更新按钮会触发udp.vue里面的方法调用后端verifyProcessDefinitionName(projects/${state.projectName}/process/verify-name)
image
其实在点击更新按钮的时候，在浏览器控制台也可以看见先请求verifyProcessDefinitionName(projects/${state.projectName}/process/verify-name)  
在请求updateProcessDefinition(projects/${state.projectName}/process/update)
image
image

如果是直接调用API方式，就需要考虑一下目前是存在两个方法都进行了工作流定义名称验证，如何更好的设计

**Comment by lgcareer** [comment]
@zhuangchong  Hello,What I said is the frontend didn't execute the verifyProcessDefinitionName on the release 1.3.3-release.But I saw your picture pasted execute the verfiyProcessDefinitionName,Which branch you tested?

**Comment by lgcareer** [comment]
image

**Comment by zhuangchong** [comment]
@lgcareer 
I tested the dev branch, and 1.3.3-release did not check the name of the workflow definition first when the workflow definition was updated. 1.3.3-release Modify the judgment conditions of the verification in udp.vue, which can be consistent with the dev branch
image


---
我测试的是dev分支，1.3.3-release 没有在工作流定义更新时候，没有先去检查工作流定义名称。1.3.3-release 修改udp.vue 内执行验证的判断条件，可与dev分支保持一致
image

**Comment by lgcareer** [comment]
@zhuangchong Great,I think it's ok.

**Pull request merged**
