### PR TITLE
chrry-pick sqoop task in dev to 1.3.4

### PR DESCRIPTION
**Pull request by Eights-Li**
## What is the purpose of the pull request

*Merge sqoop optimization and bug fix in dev-branch to 1.3.4*

## Brief change log
  - *sqoop task optimization*

## Verify this pull request

This change added tests and can be verified as follows:

  - *verified this pr using SqoopTaskTest*

### CODE REVIEW

**Comment by lenboo** [comment]
which issues does this pr refer to ?

**Comment by Eights-Li** [comment]
> which issues does this pr refer to ?

linked issue: #2917 #4034 #4104 #4135

**Review by CalvinKirs — APPROVED** [review]
server code +1

**Review by break60 — APPROVED** [review]
+1

**Review by lenboo — APPROVED** [review]
+1

**Review by lgcareer — APPROVED** [review]
+1

**Pull request merged**
