### PR TITLE
[Feature-3701][ui] Shortcut connection action for node in same flow

### PR DESCRIPTION
**Pull request by kuroikenshi**
* Set pre-tasks to get current node connect to pre-nodes automatically.
* Only SHELL and SUB-PROCESS node enabled this method.

This closes [#3701](https://github.com/apache/incubator-dolphinscheduler/issues/3701)

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Please create an issue before submit a pr, Thx a lot~

**Review by break60 — APPROVED** [review]
+1

**Comment by kuroikenshi** [comment]
> Please create an issue before submit a pr, Thx a lot~

I have just created an issue:
[issue/3071](https://github.com/apache/incubator-dolphinscheduler/issues/3701)

What should I supposed to do next ?

**Review by dailidong — APPROVED** [review]
+1
good job， thanks for your first contribution, looking forward to your deep participation

**Pull request merged**
