### PR TITLE
(Abandoned) Please go to #2970 PR.

### PR DESCRIPTION
**Pull request by 743294668**
## What is the purpose of the pull request

This pull request modify the JDBC format of the Oracle database connection.
Number:#2791.
pull/2792 ，pull/2818has been abandoned for other reasons.

The Oracle JDBC link I verified currently supports the following three methods:
jdbc:oracle:thin:@host:port:SID
jdbc:oracle:thin:@//host:port/service_name
jdbc:oracle:thin:@host:port/service_name
The above three methods are verified in the unit test.

## Brief change log

DataSourceService.java:
Add Oracle link type parameter in buildParameter().
BaseDataSource.java:
Modify appendDatabase () method as a protected modifier to facilitate OracleDataSource to rewrite this method.
OracleDataSource.java:
Override appendDatabase () method.
OracleDataSourceTest.java:
Unit test the newly modified code.
DataSourceServiceTest.java:
Add buildParameter () unit test.
pom.xml:
added a line in the maven-surefire-plugin section of the pom file to ensure that my OracleDataSourceTest.java file can be executed, thus ensuring my code coverage.

## Verify this pull request

This change added tests and can be verified as follows:

Add the Oracle data source in the data source center, including using the service name or SID.
Perform the task of executing the Oracle data source on the SQL type node and pass the verification.
##Addition

If anything is wrong, you are welcome to participate in the discussion. Thanks.

### CODE REVIEW

**Comment by 743294668** [comment]
> It's better not to change the scope of appendDatabase. You can override the getJdbcUrl directly

At first I did getJdbcUrl modified, and then I noticed #2812 modification, I made changes based on this basis, and covered appendDatabase.
For now, do you want to rewrite getJdbcUrl instead? Any other suggestions? Looking forward for your response, thank you

**Comment by gabrywu** [comment]
> > It's better not to change the scope of appendDatabase. You can override the getJdbcUrl directly
> 
> At first I did getJdbcUrl modified, and then I noticed #2812 modification, I made changes based on this basis, and covered appendDatabase.
> For now, do you want to rewrite getJdbcUrl instead? Any other suggestions? Looking forward for your response, thank you

Oh dev-1.3.0 branch the getJdbcUrl method removed, maybe we should invite @lgcareer  to review this PR

**Comment by 743294668** [comment]
@lgcareer  can you help review this? Thank you. Please explain if there is any problem.

**Comment by lgcareer** [comment]
> @lgcareer can you help review this? Thank you. Please explain if there is any problem.

image

**Comment by lgcareer** [comment]
> @lgcareer can you help review this? Thank you. Please explain if there is any problem.

You can test use "/" before sid,such as jdbc:oracle:thin:@//<host>:1521/SID,I think we didn't must use ":" before sid.

**Comment by 743294668** [comment]
> > @lgcareer can you help review this? Thank you. Please explain if there is any problem.
> 
> You can test use "/" before sid,such as jdbc:oracle:thin:@//:1521/SID,I think we didn't must use ":" before sid.

Regarding the format of the URL, I am pretty sure that I will list it again. Before submitting this code, I used the local mode to run the API module test. Only the above three methods can pass. Regarding the question you mentioned, I conducted a query on Google again, and I did not find this way of using "/" to connect sid. It may be that the author's sid and service_name have the same name.
look forward to your reply. Thank you.

**Comment by lgcareer** [comment]
> > > @lgcareer can you help review this? Thank you. Please explain if there is any problem.
> > 
> > 
> > You can test use "/" before sid,such as jdbc:oracle:thin:@//:1521/SID,I think we didn't must use ":" before sid.
> 
> Regarding the format of the URL, I am pretty sure that I will list it again. Before submitting this code, I used the local mode to run the API module test. Only the above three methods can pass. Regarding the question you mentioned, I conducted a query on Google again, and I did not find this way of using "/" to connect sid. It may be that the author's sid and service_name have the same name.
> look forward to your reply. Thank you.

If you test it and it can't work successful,I think you can use your code instead of I said,May be you are right,The last time I test successful is that the service_name and SID is consistent.

**Comment by 743294668** [comment]
@gabrywu can you help review this? Thank you. Now I don’t know who I should check with, because I see that you did a requested changes.
Please explain if there is any problem.

**Comment by 743294668** [comment]
> It's better not to change the scope of appendDatabase. You can override the getJdbcUrl directly

lgcareer has reviewed the code, this method is no problem. The restriction also requires you to modify and review it, thank you

**Comment by gabrywu** [comment]
> > It's better not to change the scope of appendDatabase. You can override the getJdbcUrl directly
> 
> lgcareer has reviewed the code, this method is no problem. The restriction also requires you to modify and review it, thank you

done,thanks for your contribution

**Comment by gabrywu** [comment]
@743294668 Because the original branch of your repo , this PR can't be merged , so could you create another branch and PR to resolve this ?

**Comment by 743294668** [comment]
> @743294668 Because the original branch of your repo , this PR can't be merged , so could you create another branch and PR to resolve this ?

Thanks for your reminder. I resubmitted a PR at #2970.

**Comment by gabrywu** [comment]
> > @743294668 Because the original branch of your repo , this PR can't be merged , so could you create another branch and PR to resolve this ?
> 
> Thanks for your reminder. I resubmitted a PR at #2970.

merged

**Pull request closed without merging**
