### PR TITLE
[Fix][Docker] fix startup.sh variables cannot reference in single quotes.

### PR DESCRIPTION
**Pull request by spring-bu**
Signed-off-by: Youngman <bushengquan@gmail.com>

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*This pull request fix startup.sh variables cannot reference in single quotes. (#3894)*

## Brief change log

  - *Fix docker/build/startu.sh a variables without single quotes (#3894)*
  - *Add mysql-client in Dockerfile to support  mysql as backend database.*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Review by qiaozhanwei — COMMENTED** [review]
great . but dockerfile can use mysql ? mysql license is gpl . please check

**Comment by spring-bu** [comment]
> great . but dockerfile can use mysql ? mysql license is gpl . please check

Although MySQL is owned by the Oracle company, we usually discuss MySQL only in the community server edition, it is open-source, we only use its client tools, if you think we should not use it, we have other options, use MariaDB-client, It is 100% compatible with MySQL.

**Comment by dailidong** [comment]
> > great . but dockerfile can use mysql ? mysql license is gpl . please check
> 
> Although MySQL is owned by the Oracle company, we usually discuss MySQL only in the community server edition, it is open-source, we only use its client tools, if you think we should not use it, we have other options, use MariaDB-client, It is 100% compatible with MySQL.

MariaDB is distributed under the GPL license, version 2. The MariaDB client libraries for C, Java and ODBC are distributed under the LGPL license, version 2.1 or later. The LGPL license allows you to distribute these MariaDB client libraries freely with any application.

so we can't use MariaDB client, GPL or LGPL not compitable with Apache license

**Review by dailidong — APPROVED** [review]
I updated the comment and delete maridb client because of LGPL license not comitable with Apache license

+1

**Pull request merged**
