### PR TITLE
[Feature-3988][UI] Enhance user experience, add close button to file details page

### LINKED ISSUE #3988: [Improvement][UI] Enhance user experience, add close button to file details page
Enhance user experience, add close button to file details page

image

### PR DESCRIPTION
**Pull request by BoYiZhang**
Enhance user experience, add close button to file details page

image

this close #3988

### CODE REVIEW

**Comment by BoYiZhang** [comment]
Only changed the web page, not the Java code

Why are the following errors reported?


------------------------------

Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project dolphinscheduler-server: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/incubator-dolphinscheduler/incubator-dolphinscheduler/dolphinscheduler-server/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :dolphinscheduler-server
Error: Process completed with exit code 1.

**Comment by CalvinKirs** [comment]
> Only changed the web page, not the Java code
> 
> Why are the following errors reported?
> 
> Error: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project dolphinscheduler-server: There are test failures.
> Error:
> Error: Please refer to /home/runner/work/incubator-dolphinscheduler/incubator-dolphinscheduler/dolphinscheduler-server/target/surefire-reports for the individual test results.
> Error: Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> Error: -> [Help 1]
> Error:
> Error: To see the full stack trace of the errors, re-run Maven with the -e switch.
> Error: Re-run Maven using the -X switch to enable full debug logging.
> Error:
> Error: For more information about the errors and possible solutions, please read the following articles:
> Error: [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> Error:
> Error: After correcting the problems, you can resume the build with the command
> Error: mvn -rf :dolphinscheduler-server
> Error: Process completed with exit code 1.

This is not your problem, I will fix it.I have helped you rerun UT

**Comment by break60** [comment]
Please solve sonar

**Comment by BoYiZhang** [comment]
> Please solve sonar


Only changed the web code, not the Java code

So there is no coverage on new code

**Comment by break60** [comment]
> > Please solve sonar
> 
> Only changed the web code, not the Java code
> 
> So there is no coverage on new code

image

**Pull request closed without merging**
