### PR TITLE
Add mail server configuration description information

### PR DESCRIPTION
**Pull request by yh2388**
More tips for mail server configuration.

### CODE REVIEW

**Comment by yh2388** [comment]
> These notes are more suitable for install.sh

So remove note of alert.properties?

**Comment by Eights-Li** [comment]
> > These notes are more suitable for install.sh
> 
> So remove note of alert.properties?

yes, install.sh more suitable

**Comment by yh2388** [comment]
> > > These notes are more suitable for install.sh
> > 
> > 
> > So remove note of alert.properties?
> 
> yes, install.sh more suitable

ok, I will do that

**Comment by dailidong** [comment]
thanks for your first contribution，looking forward for your next contribution.

best regards

**Pull request merged**
