### PR TITLE
return result state for each interface method

### PR DESCRIPTION
**Pull request by runningdata**
Queue operation should has the result state

### CODE REVIEW

**Comment by runningdata** [comment]
> Hi, bro, thanks for contribution.
> this pr looks not useful, it we add return value for these methods, we should use the return value to decide something. such as ： if add method return false, we may log or retry, but doing nothing . These methods you modify have printed the log, it's enough .
> So do you agree me ?

Yes, I agree. I don't know **the context**. Those who know their own context should handle this.

But the interface should has the return value to indicate whether the operation is successed. All exceptions now has been passed, without any alert to interface API user.

**Comment by Technoboy-** [comment]
> > Hi, bro, thanks for contribution.
> > this pr looks not useful, it we add return value for these methods, we should use the return value to decide something. such as ： if add method return false, we may log or retry, but doing nothing . These methods you modify have printed the log, it's enough .
> > So do you agree me ?
> 
> Yes, I agree. I don't know **the context**. Those who know their own context should handle this.
> 
> But the interface should has the return value to indicate whether the operation is successed. All exceptions now has been passed, without any alert to interface API user.

Yes.  But add return value according to executing without error or not is not accurate.

**Comment by runningdata** [comment]
> > > Hi, bro, thanks for contribution.
> > > this pr looks not useful, it we add return value for these methods, we should use the return value to decide something. such as ： if add method return false, we may log or retry, but doing nothing . These methods you modify have printed the log, it's enough .
> > > So do you agree me ?
> > 
> > 
> > Yes, I agree. I don't know **the context**. Those who know their own context should handle this.
> > But the interface should has the return value to indicate whether the operation is successed. All exceptions now has been passed, without any alert to interface API user.
> 
> Yes. But add return value according to executing without error or not is not accurate.

FYI

**Comment by runningdata** [comment]
> > > Hi, bro, thanks for contribution.
> > > this pr looks not useful, it we add return value for these methods, we should use the return value to decide something. such as ： if add method return false, we may log or retry, but doing nothing . These methods you modify have printed the log, it's enough .
> > > So do you agree me ?
> > 
> > 
> > Yes, I agree. I don't know **the context**. Those who know their own context should handle this.
> > But the interface should has the return value to indicate whether the operation is successed. All exceptions now has been passed, without any alert to interface API user.
> 
> Yes. But add return value according to executing without error or not is not accurate.

Why it's not accurate? What do you mean?

**Comment by Technoboy-** [comment]
> > > > Hi, bro, thanks for contribution.
> > > > this pr looks not useful, it we add return value for these methods, we should use the return value to decide something. such as ： if add method return false, we may log or retry, but doing nothing . These methods you modify have printed the log, it's enough .
> > > > So do you agree me ?
> > > 
> > > 
> > > Yes, I agree. I don't know **the context**. Those who know their own context should handle this.
> > > But the interface should has the return value to indicate whether the operation is successed. All exceptions now has been passed, without any alert to interface API user.
> > 
> > 
> > Yes. But add return value according to executing without error or not is not accurate.
> 
> FYI

I meant :  return true is not accurate when executing without exception .  srem or sadd may return false due to zk not has the relative value .  it's like -- update in MySQL, the return value represents for the influence count.

**Comment by dailidong** [comment]
as Tboy said, it's seemly no sense.  this pr will close.

thanks for your first contribution,  if you have interesting in developing DS, you can contact my mail: dailidong66@gmail.com or wechat: 510570367,  when contacted , please tell me your github id, that I can easily recognize you.

Best regards

**Pull request closed without merging**
