### PR TITLE
optimize code

### PR DESCRIPTION
**Pull request by Wuv1Up**
## What is the purpose of the pull request

optimized code

## Brief change log
remove code to correct position

## Verify this pull request
This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Please explain why this changes can optimize shellTask in your pr comment. Thx a lot~

**Comment by dailidong** [comment]
> Please explain why this changes can optimize shellTask in your pr comment. Thx a lot~

I think what he do will improve performance on windows environment，but a little pity, ds not supprot windows yet

**Comment by dailidong** [comment]
we have unified the code style , please referer `how to config check style`:  https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

**Comment by Wuv1Up** [comment]
> we have unified the code style , please referer `how to config check style`: https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

**Comment by Wuv1Up** [comment]
> we have unified the code style , please referer `how to config check style`: https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

Please wait,  i will submit the pr again for code style.

**Comment by dailidong** [comment]
please submit a new PR, thx, I will close this PR

**Pull request closed without merging**
