### PR TITLE
[bugfix] Default JVM parameter bug  

### PR DESCRIPTION
**Pull request by BoYiZhang**
Setting '-XX:+DisableExplicitGC ' causes netty memory leaks

in addition

Set '- xms1g' but '- XX: largepagesizeinbytes = 128M'

set "- XX: largepagesizeinbytes = 128M"  to "-XX:LargePageSizeInBytes=10M" 

#3198

### CODE REVIEW

**Comment by CalvinKirs** [comment]
please resolve conflicting files . Thx

**Comment by CalvinKirs** [comment]
Hi, please link the issue to this PR so that when your PR is merged, the related issue can be automatically closed.

**Comment by CalvinKirs** [comment]
this close #3198

**Comment by BoYiZhang** [comment]
> Hi, please link the issue to this PR so that when your PR is merged, the related issue can be automatically closed.

#3198

**Pull request merged**
