### PR TITLE
[FEATURE-736] integrate ldap authentication

### PR DESCRIPTION
**Pull request by geosmart**
## What is the purpose of the pull request
impletments FAETURE [#736] to integrate ldap authentication

## Brief change log
*(for example:)*
  - format code in package `org.apache.dolphinscheduler.api.security`
  - add ldap config in `application-api.properties`,config use online mock ldap server
  - core logic in `LdapAuthenticator`(for user login ) and `LdapService` (for ldap auth)
 
## Verify this pull request
This change added tests and can be verified as follows:

*(example:)*
  - Added LdapAuthenticatorTest to test authenticate.
  - Added LdapServiceTest to test ldap auth.
  - Change SecurityConfigTest  to SecurityConfigPassWordTest fro password auth.
  - Added SecurityConfigLDAPTest  fro ldapauth.
  - refactor authentication with ldap and password

### CODE REVIEW

**Comment by geosmart** [comment]
> # [Codecov](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743?src=pr&el=h1) Report
> > Merging [#3743](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743?src=pr&el=desc) into [dev](https://codecov.io/gh/apache/incubator-dolphinscheduler/commit/3942740941533721694ceef2177c5363b0d0f200?el=desc) will **decrease** coverage by `0.02%`.
> > The diff coverage is `37.86%`.
> 
> [Impacted file tree graph](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743?src=pr&el=tree)
> 
> ```diff
> @@             Coverage Diff              @@
> ##                dev    #3743      +/-   ##
> ============================================
> - Coverage     39.98%   39.96%   -0.03%     
> - Complexity     2901     2908       +7     
> ============================================
>   Files           457      460       +3     
>   Lines         21665    21726      +61     
>   Branches       2637     2642       +5     
> ============================================
> + Hits           8662     8682      +20     
> - Misses        12185    12229      +44     
> + Partials        818      815       -3     
> ```
> 
> [Impacted Files](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743?src=pr&el=tree)	Coverage Δ	Complexity Δ	
> [...nscheduler/api/security/impl/ldap/LdapService.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlY3VyaXR5L2ltcGwvbGRhcC9MZGFwU2VydmljZS5qYXZh)	`5.40% <5.40%> (ø)`	`2.00 <2.00> (?)`	
> [...che/dolphinscheduler/api/service/UsersService.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlcnZpY2UvVXNlcnNTZXJ2aWNlLmphdmE=)	`74.77% <42.85%> (+0.41%)`	`81.00 <1.00> (+1.00)`	
> [...uler/api/security/impl/ldap/LdapAuthenticator.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlY3VyaXR5L2ltcGwvbGRhcC9MZGFwQXV0aGVudGljYXRvci5qYXZh)	`87.50% <87.50%> (ø)`	`3.00 <3.00> (?)`	
> [...phinscheduler/api/security/AuthenticationType.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlY3VyaXR5L0F1dGhlbnRpY2F0aW9uVHlwZS5qYXZh)	`100.00% <100.00%> (ø)`	`2.00 <0.00> (ø)`	
> [.../dolphinscheduler/api/security/SecurityConfig.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlY3VyaXR5L1NlY3VyaXR5Q29uZmlnLmphdmE=)	`68.42% <100.00%> (+3.71%)`	`5.00 <0.00> (+1.00)`	
> [...duler/api/security/impl/AbstractAuthenticator.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlY3VyaXR5L2ltcGwvQWJzdHJhY3RBdXRoZW50aWNhdG9yLmphdmE=)	`100.00% <100.00%> (ø)`	`8.00 <2.00> (?)`	
> [...r/api/security/impl/pwd/PasswordAuthenticator.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlY3VyaXR5L2ltcGwvcHdkL1Bhc3N3b3JkQXV0aGVudGljYXRvci5qYXZh)	`100.00% <100.00%> (ø)`	`2.00 <2.00> (?)`	
> [...er/master/processor/queue/TaskResponseService.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1zZXJ2ZXIvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvc2VydmVyL21hc3Rlci9wcm9jZXNzb3IvcXVldWUvVGFza1Jlc3BvbnNlU2VydmljZS5qYXZh)	`33.33% <0.00%> (-21.57%)`	`5.00% <0.00%> (-1.00%)`	
> [...rver/master/processor/queue/TaskResponseEvent.java](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree#diff-ZG9scGhpbnNjaGVkdWxlci1zZXJ2ZXIvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvc2VydmVyL21hc3Rlci9wcm9jZXNzb3IvcXVldWUvVGFza1Jlc3BvbnNlRXZlbnQuamF2YQ==)	`49.01% <0.00%> (-9.81%)`	`9.00% <0.00%> (-5.00%)`	
> ... and [4 more](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743/diff?src=pr&el=tree-more)			
> [Continue to review full report at Codecov](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743?src=pr&el=footer). Last update [3942740...cd375d8](https://codecov.io/gh/apache/incubator-dolphinscheduler/pull/3743?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by geosmart** [comment]
LdapService.java need Ldap service to test, the online demo ldap service is not stable for continue delivery.
so I didn't add LdapServiceTest.java to the pom file

**Review by felix-thinkingdata — COMMENTED** [review]
dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java

Is this abstraction necessary?

这种抽象有没有必要？

**Comment by geosmart** [comment]
> dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java
> 
> Is this abstraction necessary?
> 
> 这种抽象有没有必要？

if I don't refactor a AbstractAuthenticator , sonar will detect the duplicate and can not pass...

**Comment by felix-thinkingdata** [comment]
ok  i see😅😅😅发自我的iPhone------------------ Original ------------------From: geosmart  <notifications@github.com>Date: Tue,Sep 15,2020 9:19 AMTo: apache/incubator-dolphinscheduler <incubator-dolphinscheduler@noreply.github.com>Cc: felix.wang <felix@thinkingdata.cn>, Comment <comment@noreply.github.com>Subject: Re: [apache/incubator-dolphinscheduler] [FEATURE-736] integrate ldapauthentication (#3743)



dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java

Is this abstraction necessary?

这种抽象有没有必要？



if I don't refactor a AbstractAuthenticator , sonar will detect the duplicate and can not pass...



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/apache/incubator-dolphinscheduler/pull/3743#issuecomment-692402838",

"url": "https://github.com/apache/incubator-dolphinscheduler/pull/3743#issuecomment-692402838",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Review by felix-thinkingdata — APPROVED** [review]

**Review by CalvinKirs — COMMENTED** [review]
+1, @dailidong  hi,this pr belongs to a sub-future of a big future, can we merge this pr immediately, or do we need to wait for all futures to be completed?

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
