### PR TITLE
[Feature-docker][ui] Update dolphinscheduler.conf

### PR DESCRIPTION
**Pull request by shi-hailong**
/ui下的资源访问不应该发送到api-server

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*(For example: This pull request adds checkstyle plugin.)*

## Brief change log

*(for example:)*
  - *Add maven-checkstyle-plugin to root pom.xml*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by gabrywu** [comment]
@shi-hailong Please resolve Unit Test failed

**Comment by felix-thinkingdata** [comment]
> @shi-hailong Please resolve Unit Test failed

 UT MODULE  gc problem,Refer to this solution #3264，Comment out those GC problem tests

**Comment by dailidong** [comment]
> @shi-hailong Please resolve Unit Test failed

this is not his problem,he just change nginx config

**Comment by dailidong** [comment]
thanks for your first contribution, looking forward to your next contribution, if you need any help, please send mail to dev@dolphinscheduler.apache.org or contact my wechat(510570367), when added, please tell me your github id, thx

**Pull request merged**
