### PR TITLE
rename menu name ”Yarn Queue Manage” to ”Queue Manage”

### PR DESCRIPTION
**Pull request by kevinsun2010**
##  What is the purpose of the pull request
rename menu name   Yarn 队列管理 to 队列管理  ，the name is  no relationship with yarn 。so is named Yarn 队列管理 is not fit。

### CODE REVIEW

**Comment by xingchun-chen** [comment]
When running MR, spark, and flink tasks, the queue will be associated. The queue is the yarn queue. Therefore, in order to distinguish between DS and yarn queues, the queue management is changed to Yarn queue management

**Comment by kevinsun2010** [comment]
> When running MR, spark, and flink tasks, the queue will be associated. The queue is the yarn queue. Therefore, in order to distinguish between DS and yarn queues, the queue management is changed to Yarn queue management

MR, spark, and flink tasks  only part task not all task need yarn，DS  should not  bind yarn ，queue  only means worker group  。  it is only  myself view。

**Comment by BoYiZhang** [comment]
It was called queue management before, which caused a lot of trouble to users.
Many people think that it is the queue when ds is performing tasks.

In fact, it is a yarn queue, which only serves spark, flink, and mr.

**Comment by dailidong** [comment]
> > When running MR, spark, and flink tasks, the queue will be associated. The queue is the yarn queue. Therefore, in order to distinguish between DS and yarn queues, the queue management is changed to Yarn queue management
> 
> MR, spark, and flink tasks only part task not all task need yarn，DS should not bind yarn ，queue only means worker group 。 it is only myself view。

do you have any good ideas?  or Where do you think the queue name is more appropriate？

**Comment by kevinsun2010** [comment]
> > > When running MR, spark, and flink tasks, the queue will be associated. The queue is the yarn queue. Therefore, in order to distinguish between DS and yarn queues, the queue management is changed to Yarn queue management
> > 
> > 
> > MR, spark, and flink tasks only part task not all task need yarn，DS should not bind yarn ，queue only means worker group 。 it is only myself view。
> 
> do you have any good ideas? or Where do you think the queue name is more appropriate？
> 

when creating  MR, spark, and flink tasks not found how to  set queue param，Excuse me, how to use queue 。

**Pull request closed without merging**
