### PR TITLE
[Feature-3749][Alert-SPI] SqlTask should send notifications by alert server api

### PR DESCRIPTION
**Pull request by zhuangchong**
#3749 

## What is the purpose of the pull request

In this feature , Alert server is a message notification service , email and wechat is a plugin of this service . If you want send email message you can create an instance of email plugin in the alert group and then you can select the alert group in SqlTask . SqlTask can call the alert server api with this alert group arrguement to send the message.

So we need alert api to support other service invoke.

Now the alert service sends alarms abnormally by periodically scanning the records in table t_ds_alert. It is asynchronous.

In the SqlTask task case, the task need send message synchronous and the final running status of this task depends on whether the message is sent successfully. So the alert api need send messages synchronously.

### CODE REVIEW

**Comment by gaojun2048** [comment]
Why test  coverage only 8.3%?

**Comment by zhuangchong** [comment]
> Why test coverage only 8.3%?

The test class has been written, but the coverage is 0, and no reason has been found

**Comment by gaojun2048** [comment]
> > Why test coverage only 8.3%?
> 
> The test class has been written, but the coverage is 0, and no reason has been found

Can you run the test coverage in your IDE and upload a image of the coverage ?

**Comment by zhuangchong** [comment]
> > > Why test coverage only 8.3%?
> > 
> > 
> > The test class has been written, but the coverage is 0, and no reason has been found
> 
> Can you run the test coverage in your IDE and upload a image of the coverage ?

@gaojun2048 @CalvinKirs  Please help to review.
image

**Comment by gaojun2048** [comment]
Because we use PowerMock in this ut, So the SonarCloud Code Analysis  can not get the test coverage. From your image I think the test coverage is ok.

**Review by gaojun2048 — APPROVED** [review]
+1

**Comment by gaojun2048** [comment]
+1

**Review by CalvinKirs — APPROVED** [review]
server code +1

**Pull request merged**
