### PR TITLE
Hourly dependency configuration， 'currentHour' and 'last24Hours'

### PR DESCRIPTION
**Pull request by xuchangqun**
The pull request add two dependent type , 'current hour' and 'last24Hours'

[Feature] Hourly dependency configuration #2680

### CODE REVIEW

**Comment by dailidong** [comment]
SonarCloud Quality Gate failed.  please add UT test for the new code

**Comment by break60** [comment]
frontend +1

**Comment by dailidong** [comment]
@lenboo please review this PR, thanks

**Comment by lenboo** [comment]
@xuchangqun please add a description in title.

**Pull request merged**
