### PR TITLE
[checkstyle] optimize java code checkstyle for FileTabCharacter rule

### PR DESCRIPTION
**Pull request by lamber-ken**
## What is the purpose of the pull request

optimize java code checkstyle for FileTabCharacter rule

## Brief change log

optimize java code checkstyle for FileTabCharacter rule

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by khadgarmage** [comment]
please track the root issue #1461, thanks

**Comment by lamber-ken** [comment]
> #1461

没有看明白 #1461 什么意思

**Comment by khadgarmage** [comment]
> > #1461
> 
> 没有看明白 #1461 什么意思

就是现在ci/cd都统一规划了一下，你可以每次提交PR的之后链接上这个根issue，方便后续追踪，还有你现在用的是google的规范吗

**Comment by lamber-ken** [comment]
👌

**Pull request closed without merging**
