### PR TITLE
[Feature-2127][sql-schema] Fix the mysql version limited error (#2127)

### PR DESCRIPTION
**Pull request by yangyichao-mango**
## What is the purpose of the pull request

*Fix the mysql version and datetime sql syntax limited error for 5.5x - 5.64.*

## Brief change log

  - *Remove the CURRENT_TIMESTAMP in sql file.*
  - *Change the sql datetime(0) syntax to common syntax datetime, because mysql5.5x does not support the datetime(0) syntax, and datetime syntax is be in common use in mysql5.x and mysql8.x.*
  - *There is no need to set datetime in java code, because the default time was set up before.*

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by dailidong** [comment]
good idea.

if remove default time set in sql file, but create_time and update_time is not set in java code in 1.0 version(you can check the code, I'm not remember clearly),  system will not work fine

**Comment by yangyichao-mango** [comment]
> good idea.
> 
> if remove default time set in sql file, but create_time and update_time is not set in java code in 1.0 version(you can check the code, I'm not remember clearly), system will not work fine

Thx for your review.
The java code has done the setter operation for create_time and update_time in previous version.
I've checked the java code and deployed the app to test this part.
When I do insert operation, it will generate create_time and update_time in db correctly.

**Comment by yangyichao-mango** [comment]
> good idea.
> 
> if remove default time set in sql file, but create_time and update_time is not set in java code in 1.0 version(you can check the code, I'm not remember clearly), system will not work fine

Thx for your review.
Do I need to check all the released version and fix that issue?

**Comment by yangyichao-mango** [comment]
> good idea.
> 
> if remove default time set in sql file, but create_time and update_time is not set in java code in 1.0 version(you can check the code, I'm not remember clearly), system will not work fine

Thx for your review.

I've checked all the active dev branch and fixed [2127](https://github.com/apache/incubator-dolphinscheduler/issues/2127) in those dev branch.

**Comment by dailidong** [comment]
good job,  please contact me(lidongdai@apache.org) or wechat(510570367) , when added, please tell me your github id, thx

**Pull request merged**
