### PR TITLE
[Improvement-3686][service] ProcessService method name meets naming convention.

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request

#3686 
ProcessService method name meets naming convention.

## Brief change log

1.ProcessService .delCommandByid Change to delCommandById
2.ProcessService .queryUdfFunListByids Change to queryUdfFunListByIds

3.ProcessService  add code checkstyle

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Review by AhahaGe — APPROVED** [review]
I have a glance of code, most of them are checkStyle change, no error found.

**Comment by yangyichao-mango** [comment]
Please resolve check fail

**Comment by zhuangchong** [comment]
> Please resolve check fail

This failure is a bit incomprehensible, I only submitted two class files, no errors were reported

**Comment by zhuangchong** [comment]
@dailidong @CalvinKirs done. Please help to review.

---
1.ProcessService .delCommandByid Change to delCommandById
2.ProcessService .queryUdfFunListByids Change to queryUdfFunListByIds
3.ProcessService add code checkstyle

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Review by dailidong — APPROVED** [review]
+1
good job

**Pull request merged**
