### PR TITLE
[Improvement][checkstyle] add check style file to alert_plugin_design branch

### PR DESCRIPTION
**Pull request by gaojun2048**
issue: https://github.com/apache/incubator-dolphinscheduler/issues/3678

### CODE REVIEW

**Comment by yangyichao-mango** [comment]
Please resolve conflicts.

**Comment by gaojun2048** [comment]
> Please resolve conflicts.

ok ! I solve it

**Comment by yangyichao-mango** [comment]
The checkstyle is the same with dev branch. There is no need to change it.
image

**Comment by gaojun2048** [comment]
> The checkstyle is the same with dev branch. There is no need to change it.
> image

ok, I close it

**Pull request closed without merging**
