### PR TITLE
[fix-4128][worker] Dolphin executes the command using sudo to specify the -u parameter

### LINKED ISSUE #4128: [BUG][worker] Dolphin executes the command using sudo to specify the -u parameter
**Describe the feature**
Dolphin executes the command using sudo to specify the -u parameter

sudo:
-u Username /#uid without this parameter means that you want to execute the instruction as root
At present, dolphin source code exists sudo kill $PID /sudo kill -9 $PID situation
Executing the above statement will report insufficient permissions when dolphin installs THE OS user's sudo permissions with only a partial user account configuration.

**Is your feature request related to a problem? Please describe.**

At present, dolphin source code exists sudo kill $PID /sudo kill -9 $PID situation
Executing the above statement will report insufficient permissions when dolphin installs THE OS user's sudo permissions with only a partial user account configuration.

---
**描述特征**

dolphin使用sudo 执行命令指定-u 参数
sudo：
	-u username/#uid 不加此参数，代表要以 root 的身份执行指令
目前dolphin源码内存在sudo kill $pid /sudo kill -9 $pid 的情况
当dolphin 安装os用户的sudo权限只配置部分用户账号时，执行上面语句将会报出权限不足。

**您的特性请求与问题有关吗?请描述**

目前dolphin源码内存在sudo kill $pid /sudo kill -9 $pid 的情况
当dolphin 安装os用户的sudo权限只配置部分用户账号时，执行上面语句将会报出权限不足。

### PR DESCRIPTION
**Pull request by zhuangchong**
## What is the purpose of the pull request

this closes #4128 
Dolphin executes the command using sudo to specify the -u parameter

sudo:
-u username /#uid without this parameter means that you want to execute the instruction as root
At present, dolphin source code exists sudo kill $PID /sudo kill -9 $PID situation
Executing the above statement will report insufficient permissions when dolphin installs THE OS user's sudo permissions with only a partial user account configuration.

## Brief change log
* sudo kill $PID changed to sudo -u username kill $PID

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.*

---
## pull request的目的是什么

dolphin使用sudo 执行命令指定-u 参数
sudo：
-u username/#uid 不加此参数，代表要以 root 的身份执行指令
目前dolphin源码内存在sudo kill $pid /sudo kill -9 $pid 的情况
当dolphin 安装os用户的sudo权限只配置部分用户账号时，执行上面语句将会报出权限不足。

## 简短的更改日志

sudo kill $PID 更改为 sudo -u username kill $PID

### CODE REVIEW

**Comment by dailidong** [comment]
good job
I think this PR could do more, considering the following choise:
1. Whether to use multi-tenant, 2. Use multi-tenant and configure sudo permissions

**Comment by zhuangchong** [comment]
> good job
> I think this PR could do more, considering the following choices: 1. Whether to use multi-tenant, 2. Use multi-tenant and configure sudo permissions

I have created issus #4515 to describe the feature. For the second point, sudo permissions can only be described in the section of cluster deployment on the official website for users to choose by themselves.

**Review by dailidong — APPROVED** [review]
+1
excellent, looking forward to completing the entire issue soon

**Comment by davidzollo** [comment]
@xingchun-chen please test this feature when you free

**Pull request merged**
