### PR TITLE
Add eslint to check frontend codes style, closes #1463

### LINKED ISSUE #1463: [CI/CD]Add Front-end eslint check
follow the root issue: #1460
Steps:
1、modify files which not satisfy the check，and pay attention not to submit too much files each time in a pr, it is better not to exceed 10, which is convenient for review, and can be split into multiple pr to submit, and the pr which you submit should follow this issue (e.g. #1463).
2、Add to github action to execute this check in ".github" directory, and we must ensure that CI / CD is successfully rebuilt, you can put the files which you modified into the maven pom.xml whitelist, to ensure the rebuilt successfully.

### PR DESCRIPTION
**Pull request by kezhenxu94**
closes #1463

### CODE REVIEW

**Comment by break60** [comment]
Add eslint to the front end, if wordwrap appears in the node_modules folder, please do not add eslint

**Comment by kezhenxu94** [comment]
> Add eslint to the front end, if wordwrap appears in the node_modules folder, please do not add eslint
> image

Your information is out of date, the license issue of word-wrap has already been fixed[1], please refer to the mailing list[2] for complete context

[1] https://github.com/substack/node-wordwrap/issues/21
[2] https://lists.apache.org/thread.html/346ea8ac79c1cdd91c6d7c6d5acb2360a1d84d3a3e8966f91d260cbf%40%3Clegal-discuss.apache.org%3E

**Comment by break60** [comment]
frontEnd +1

**Comment by kezhenxu94** [comment]
> frontEnd +1

What do you mean by saying "frontEnd +1"? It's better to follow the GitHub flow, use the review comment to indicate your opinion, like this

image

**Comment by kezhenxu94** [comment]
This PR is opened for a long time, is there any maintainer who is able to review and give me some feedback? @dailidong @chenxingchun

**Pull request merged**
